#import "../../../TypstTemplate/math-notes.typ": *

= Complex Numbers and Complex Planes // 复数与复平面
== Complex Numbers and Their Geometric Representation // 复数与其几何表示
The numbers with the form $z = x + y"i"$, where $x, y in bb(R)$ and $"i"$ is the imaginary unit satisfying $"i"^2 = -1$, are called *complex numbers*.
$x, y$ are called the real and imaginary parts of $z$ with the notation $x = Re(z)$ ($RR(z)$) 
and $y = Im(z)$ ($II(z)$), respectively.
When $y = 0$, $z$ is called a *real number*, and when $x = 0$, $z$ is called a *pure imaginary number*.

Complex numbers can be represented as points in the Cartesian coordinate system 
(*complex plane*, also known as the Argand plane, see @fig:complex_plane), 
where the horizontal axis (the real axis) represents the real part and 
the vertical axis (the imaginary axis) represents the imaginary part.

#figure(
  image("../img/Complex_conjugate_picture.svg.png", width: 25%),
  caption: [Complex number $z$ and its conjugate $overline(z)$ in the complex plane.],
  placement: auto,
  supplement: [Fig.]
) <fig:complex_plane>

$overline(z) = x - y"i"$ is called the *complex conjugate* of $z$.
It is easy to verify the following properties of complex conjugation:

1. $overline(overline(z)) = z, quad overline(z_1 plus.minus z_2) = overline(z_1) plus.minus overline(z_2)$;
2. $overline(z_1 z_2) = overline(z_1) dot overline(z_2), quad overline(z_1 slash z_2) = overline(z_1) slash overline(z_2)$;
3. $z^2 = z overline(z), quad Re(z) = (z + overline(z)) / 2, quad Im(z) = (z - overline(z)) / (2"i")$;
4. $overline(R(a, b, c, dots)) = R(overline(a), overline(b), overline(c), dots)$, where $R$ is any rational function of its arguments.

The set of all complex numbers is denoted by $bb(C)$.

#v(0.7cm)
*Field* is a set $bb(F)$ equipped with two operations (addition and multiplication) that satisfy:

1. $(bb(F), +)$ is an abelian group.
2. $(bb(F) \ {0}, dot)$ is an abelian group.
3. Multiplication is distributive over addition.

If we define addition and multiplication of complex numbers as follows:

$ (x_1 + y_1"i") + (x_2 + y_2"i") = (x_1 + x_2) + (y_1 + y_2)"i", $

$ (x_1 + y_1"i") dot (x_2 + y_2"i") = (x_1 x_2 - y_1 y_2) + (x_1 y_2 + x_2 y_1)"i", $

then $bb(C)$ forms a field, 
which is a quadratic extension of the real numbers and an algebraically closed field of characteristic zero.

Now we give several rigorous definitions of the complex number field for subsequent analysis.

#definition(name: "Complex Number")[
1. *Analytic/Ordered Pair Definition.* Let
$ 
bb(C) = {(x, y) \| x, y in bb(R)}, 
$
and define addition and multiplication as follows:
$ (x_1, y_1) + (x_2, y_2) = (x_1 + x_2, y_1 + y_2), $
$ (x_1, y_1) dot (x_2, y_2) = (x_1 x_2 - y_1 y_2, x_1 y_2 + x_2 y_1). $
Then $(bb(C), +, dot)$ is a field, called the complex field.
2. *Polynomial Quotient Ring Definition.* The quotient ring of the polynomial ring $bb(R)[x]$ by the ideal generated by $x^2 + 1$ is a field, denoted by 
$ 
bb(C) = (bb(R)[x])/(x^2 + 1), 
$
called the complex field.
3. *Matrix Definition.* Let
$ 
bb(C) = {mat(delim: "(", x, -y; y, x) \| x, y in bb(R)}. 
$
Then $(bb(C), +, dot)$ is a field, where addition and multiplication are defined as matrix addition and multiplication, respectively, called the complex field.
]

Since the field guarantees the existence of multiplicative inverses for non-zero elements,
we can define the division of complex numbers as follows:

$ z^(-1) = 1/z = overline(z)/abs(z)^2 = (x - y"i")/(x^2 + y^2). $

== Other Representations of Complex Numbers

For a non-zero complex number $z = x + y"i"$, the *argument* of $z$,
denoted by $"Arg"(z) = arctan(y/x)$, is defined as 
the angle $phi$ between the positive real axis and the line segment from the origin to the point $z$ in the complex plane, 
measured in the counterclockwise direction.

It's obvious that a complex number corresponds to infinitely many arguments, 
so we usually define the principal value $arg(z)$ to represent the unique argument in the range $(-pi, pi]$.

Moreover, we define the *modulus* of $z$ as $r = abs(z) = sqrt(x^2 + y^2)$, 
which is the distance from the origin to the point $z$ in the complex plane.
Then we can express $z$ in polar form as

$ z = r(cos phi + "i" sin phi) = r e^(i phi), $

where $e^(i phi) = cos phi + "i" sin phi$ is known as *Euler's formula*
(refer to @fig:complex_plane).

The polar representation of complex numbers allows us to conveniently perform multiplication and division,
as they correspond to the product and quotient of moduli and the sum and difference of arguments, respectively:

$ z_1 z_2 = r_1 r_2 e^(i (phi_1 + phi_2)), quad z_1 slash z_2 = r_1 slash r_2 e^(i (phi_1 - phi_2)). $

Thus, we know that multiplying two complex numbers is equivalent to multiplying their moduli and adding their arguments, while dividing two complex numbers is equivalent to dividing their moduli and subtracting their arguments.

#note[
  With the help of the polar representation of complex numbers, we can easily prove some trigonometric identities,
  such as the double-angle formulas and the sum and difference formulas.
  For example, using Euler's formula, we have

  $ e^(i 2phi) = (e^(i phi))^2 = (cos phi + "i" sin phi)^2 = cos 2phi + "i" sin 2phi, $

  which gives us the double-angle formulas:

  $ cos 2phi = 2cos^2 phi - 1, quad sin 2phi = 2sin phi cos phi. $

  Similarly, we can derive the sum and difference formulas for sine and cosine.
]

#note[
  With the help of the polar representation of complex numbers, we can rewrite the real matrix definition of the complex field
  to better understand the geometric meaning of complex numbers:
  
  Let
  $ 
  bb(C) = mat(delim: "(", r cos phi, -r sin phi; r sin phi, r cos phi) \| r >= 0, phi in [0, 2pi) . 
  $
  Then we can verify that the addition and multiplication defined as matrix addition and multiplication, respectively, are consistent with the polar representation of complex numbers.

  When the modulus is $1$, this is the rotation matrix in analytic geometry, which represents the rotational effect of complex numbers in the complex plane.
]

== Powers and Roots of Complex Numbers

Let $z = r e^(i phi)$ be a non-zero complex number. 
For any integer $n$, we have
$ 
z^n = r^n e^(i n phi) = r^n (cos n phi + "i" sin n phi). 
$

Then it can be derived that

$
abs(z^n) = r^n, quad "Arg"(z^n) = n phi. 
$

When $r = 1$, it is called *De Moivre's formula*:

$ (cos phi + "i" sin phi)^n = cos n phi + "i" sin n phi. $

Find the $n$-th roots of $z$ is equivalent to solving the equation $omega^n = z$,
which has $n$ distinct solutions given by

$ omega_k = r^(1/n) e^(i ((phi + 2k pi)/n)) = r^(1/n) [cos ((phi + 2k pi)/n) + "i" sin ((phi + 2k pi)/n)], quad k = 0, 1, ..., n-1. $

== The Extended Complex Plane

The *extended complex plane*, denoted by $hat(bb(C))$, is defined as the union of the complex plane $bb(C)$ and the point at infinity $infinity$:

$
  hat(bb(C)) = bb(C) union {infinity}. 
$

This extension allows us to treat infinity as a point in the complex plane,
which is particularly useful in complex analysis for 
studying the behavior of functions at infinity and for compactifying the complex plane.

The extended complex plane can be visualized as a sphere, called the *Riemann sphere*, 
where the point at infinity corresponds to the north pole of the sphere.

#figure(
  image("../img/extended_complex_plane.png", width: 40%),
  caption: [The extended complex plane, also known as the Riemann sphere.],
  placement: auto,
  supplement: [Fig.]
) <fig:extended_complex_plane>

In the extended complex plane, every line intersects at the point at infinity,
so we can view the extended complex plane as a compactification of the complex plane.
This compactification allows us to apply topological and geometric methods to study complex functions,
especially those that have singularities or poles at infinity.
