#import "../../TypstTemplate/math-notes.typ": *

#set document(
  title: "Analyse Complexe",
  author: "Violet",
  date: datetime.today(),
)

#show: apply-style

// --------------------------------------------------------------------------
// Cover + Outline
// --------------------------------------------------------------------------

#make-cover(
  "Analyse Complexe",
  "Violet",
  subtitle: "A notebook for complex analysis",
  institute: "Notiz Mathematiques",
  date: datetime.today().display(),
  version: "v0.2.0",
  extra-info: "This is a notebook for complex analysis.",
)

#make-outline(depth: 2, title: "Contents")


#part("Basic Complex Analysis") // 基础复分析
= Complex Numbers and the Complex Plane // 复数与复平面
== Complex Numbers and Their Geometric Representation // 复数与其几何表示
The numbers with the form $z = x + y"i"$, where $x, y in bb(R)$ and $"i"$ is the imaginary unit satisfying $"i"^2 = -1$, are called *complex numbers*.
$x, y$ are called the real and imaginary parts of $z$ with the notation $x = Re(z)$ ($RR(z)$)
and $y = Im(z)$ ($II(z)$), respectively.
When $y = 0$, $z$ is called a *real number*, and when $x = 0$, $z$ is called a *pure imaginary number*.

Complex numbers can be represented as points in the Cartesian coordinate system
(*complex plane*, also known as the Argand plane, see @fig:complex_plane),
where the horizontal axis (the real axis) represents the real part and
the vertical axis (the imaginary axis) represents the imaginary part.

#figure(
  image("./img/Complex_conjugate_picture.svg.png", width: 25%),
  caption: [Complex number $z$ and its conjugate $overline(z)$ in the complex plane.],
  placement: auto,
  supplement: [Fig.],
) <fig:complex_plane>

$overline(z) = x - y"i"$ is called the *complex conjugate* of $z$.
It is easy to verify the following properties of complex conjugation:

1. $overline(overline(z)) = z, quad overline(z_1 plus.minus z_2) = overline(z_1) plus.minus overline(z_2)$;
2. $overline(z_1 z_2) = overline(z_1) dot overline(z_2), quad overline(z_1 slash z_2) = overline(z_1) slash overline(z_2)$;
3. $z^2 = z overline(z), quad Re(z) = (z + overline(z)) / 2, quad Im(z) = (z - overline(z)) / (2"i")$;
4. $overline(R(a, b, c, dots)) = R(overline(a), overline(b), overline(c), dots)$, where $R$ is any rational function of its arguments.

The set of all complex numbers is denoted by $bb(C)$.

#v(0.7cm)
*Field* is a set $bb(F)$ equipped with two operations (addition and multiplication) that satisfy:

1. $(bb(F), +)$ is an abelian group.
2. $(bb(F) backslash {0}, dot)$ is an abelian group.
3. Multiplication is distributive over addition.

If we define addition and multiplication of complex numbers as follows:

$ (x_1 + y_1"i") + (x_2 + y_2"i") = (x_1 + x_2) + (y_1 + y_2)"i", $

$ (x_1 + y_1"i") dot (x_2 + y_2"i") = (x_1 x_2 - y_1 y_2) + (x_1 y_2 + x_2 y_1)"i", $

then $bb(C)$ forms a field,
which is a quadratic extension of the real numbers and an algebraically closed field of characteristic zero.

Now we give several rigorous definitions of the complex number field for subsequent analysis.

#definition(name: "Complex Number")[
  1. *Analytic/Ordered Pair Definition.* Let
  $
    bb(C) = {(x, y) \| x, y in bb(R)},
  $
  and define addition and multiplication as follows:
  $ (x_1, y_1) + (x_2, y_2) = (x_1 + x_2, y_1 + y_2), $
  $ (x_1, y_1) dot (x_2, y_2) = (x_1 x_2 - y_1 y_2, x_1 y_2 + x_2 y_1). $
  Then $(bb(C), +, dot)$ is a field, called the complex field.
  2. *Polynomial Quotient Ring Definition.* The quotient ring of the polynomial ring $bb(R)[x]$ by the ideal generated by $x^2 + 1$ is a field, denoted by
  $
    bb(C) = (bb(R)[x])/(x^2 + 1),
  $
  called the complex field.
  3. *Matrix Definition.* Let
  $
    bb(C) = {mat(delim: "(", x, -y; y, x) \| x, y in bb(R)}.
  $
  Then $(bb(C), +, dot)$ is a field, where addition and multiplication are defined as matrix addition and multiplication, respectively, called the complex field.
]

Since the field guarantees the existence of multiplicative inverses for non-zero elements,
we can define the division of complex numbers as follows:

$ z^(-1) = 1/z = overline(z)/abs(z)^2 = (x - y"i")/(x^2 + y^2). $

== Polar Form and Euler's Formula // 极坐标形式与欧拉公式

For a non-zero complex number $z = x + y"i"$, the *argument* of $z$,
denoted by $"Arg"(z) = arctan(y/x)$, is defined as
the angle $phi$ between the positive real axis and the line segment from the origin to the point $z$ in the complex plane,
measured in the counterclockwise direction.

It's obvious that a complex number corresponds to infinitely many arguments,
so we usually define the principal value $arg(z)$ to represent the unique argument in the range $(-pi, pi]$.

Moreover, we define the *modulus* of $z$ as $r = abs(z) = sqrt(x^2 + y^2)$,
which is the distance from the origin to the point $z$ in the complex plane.
Then we can express $z$ in polar form as

$ z = r(cos phi + "i" sin phi) = r e^(i phi), $

where $e^(i phi) = cos phi + "i" sin phi$ is known as *Euler's formula*
(refer to @fig:complex_plane).

The polar representation of complex numbers allows us to conveniently perform multiplication and division,
as they correspond to the product and quotient of moduli and the sum and difference of arguments, respectively:

$ z_1 z_2 = r_1 r_2 e^(i (phi_1 + phi_2)), quad z_1 slash z_2 = r_1 slash r_2 e^(i (phi_1 - phi_2)). $

Thus, we know that multiplying two complex numbers is equivalent to multiplying their moduli and adding their arguments, while dividing two complex numbers is equivalent to dividing their moduli and subtracting their arguments.

#note[
  With the help of the polar representation of complex numbers, we can easily prove some trigonometric identities,
  such as the double-angle formulas and the sum and difference formulas.
  For example, using Euler's formula, we have

  $ e^(i 2phi) = (e^(i phi))^2 = (cos phi + "i" sin phi)^2 = cos 2phi + "i" sin 2phi, $

  which gives us the double-angle formulas:

  $ cos 2phi = 2cos^2 phi - 1, quad sin 2phi = 2sin phi cos phi. $

  Similarly, we can derive the sum and difference formulas for sine and cosine.
]

#note[
  With the help of the polar representation of complex numbers, we can rewrite the real matrix definition of the complex field
  to better understand the geometric meaning of complex numbers:

  Let
  $
    bb(C) = mat(delim: "(", r cos phi, -r sin phi; r sin phi, r cos phi) \| r >= 0, phi in [0, 2pi) .
  $
  Then we can verify that the addition and multiplication defined as matrix addition and multiplication, respectively, are consistent with the polar representation of complex numbers.

  When the modulus is $1$, this is the rotation matrix in analytic geometry, which represents the rotational effect of complex numbers in the complex plane.
]

== Powers and Roots of Complex Numbers

Let $z = r e^(i phi)$ be a non-zero complex number.
For any integer $n$, we have
$
  z^n = r^n e^(i n phi) = r^n (cos n phi + "i" sin n phi).
$

Then it can be derived that

$
  abs(z^n) = r^n, quad "Arg"(z^n) = n phi.
$

When $r = 1$, it is called *De Moivre's formula*:

$ (cos phi + "i" sin phi)^n = cos n phi + "i" sin n phi. $

Find the $n$-th roots of $z$ is equivalent to solving the equation $omega^n = z$,
which has $n$ distinct solutions given by

$
  omega_k = r^(1/n) e^(i ((phi + 2k pi)/n)) = r^(1/n) [cos ((phi + 2k pi)/n) + "i" sin ((phi + 2k pi)/n)], quad k = 0, 1, ..., n-1.
$

== The Extended Complex Plane

The *extended complex plane*, denoted by $hat(bb(C))$, is defined as the union of the complex plane $bb(C)$ and the point at infinity $infinity$:

$
  hat(bb(C)) = bb(C) union {infinity}.
$

This extension allows us to treat infinity as a point in the complex plane,
which is particularly useful in complex analysis for
studying the behavior of functions at infinity and for compactifying the complex plane.

The extended complex plane can be visualized as a sphere, called the *Riemann sphere*,
where the point at infinity corresponds to the north pole of the sphere.

#figure(
  image("./img/extended_complex_plane.png", width: 40%),
  caption: [The extended complex plane, also known as the Riemann sphere.],
  placement: auto,
  supplement: [Fig.],
) <fig:extended_complex_plane>

In the extended complex plane, every line intersects at the point at infinity,
so we can view the extended complex plane as a compactification of the complex plane.
This compactification allows us to apply topological and geometric methods to study complex functions,
especially those that have singularities or poles at infinity.

== Topology of the Complex Plane // 复平面的拓扑

= Complex Functions // 复函数

== Definition and Basic Properties // 定义与基本性质

== Limits and Continuity // 极限与连续性

== Differentiability and Cauchy-Riemann Equations // 可微性与柯西-黎曼方程

== Holomorphic and Analytic Functions // 全纯函数与解析函数

== Harmonic Functions // 调和函数

= Elementary Functions // 初等函数

== Exponential Function // 指数函数

== Trigonometric and Hyperbolic Functions // 三角函数与双曲函数

== Logarithmic Function // 对数函数

== Complex Powers // 复数幂

== Inverse Trigonometric Functions // 反三角函数

#part("Complex Integration") // 复积分
= Complex Integral // 复积分

== Definition and Properties of Complex Integral // 复积分的定义与性质
#definition(name: "Complex Integral")[
  Let $C: z=z(t), t in [alpha, beta]$ be an oriented curve in the complex plane starting at $a=z(alpha)$ and ending at $b=z(beta)$ and let $f(z)$ be a complex-valued function defined on $C$.

  From $a$ to $b$, take partitions of $C$ into $n$ segments by points $z_0=a, z_1, z_2, dots, z_n=b$.
  Then on each segment $z_(k-1)z_k$, take a point $xi_k$ and form the sum
  $
    sum_(k=1)^n f(xi_k)Delta z_(k), quad Delta z_(k) = z_k - z_(k-1).
  $
  If the limit of the above sum exists as the maximum length of the segments tends to zero, then we call it the *complex integral* of $f$ along $C$, denoted by
  $
    integral_C f(z) "d"z.
  $
]

#property[
  - *Linearity*: If $f$ and $g$ are integrable on $C$ and $alpha, beta in bb(C)$, then
  $
    integral_C (alpha f(z) + beta g(z)) "d"z = alpha integral_C f(z) "d"z + beta integral_C g(z) "d"z.
  $
  - *Additivity*: If $C$ is the union of two oriented curves $C_1$ and $C_2$ such that the end point of $C_1$ is the starting point of $C_2$, then
  $
    integral_C f(z) "d"z = integral_(C_1) f(z) "d"z + integral_(C_2) f(z) "d"z.
  $
  - *Reversal*: If $-C$ is the curve $C$ with the opposite orientation, then
  $
    integral_(-C) f(z) "d"z = - integral_C f(z) "d"z.
  $
  - *Estimation*: If $f$ is integrable on $C$, let $L$ be the length of $C$ and $M = max_(z in C) |f(z)|$, then
  $
    |integral_C f(z) "d"z| <= M L.
  $
]

#theorem[
  If $f(z) = u(x, y) + "i" v(x, y)$ is continuous on $C$, then $f$ is integrable on $C$ and
  $
    integral_C f(z) "d"z = integral_C u "d"x - integral_C v "d"y + "i" (integral_C v "d"x + integral_C u "d"y).
  $
]

#proposition(name: "Some Common Integrals")[
  - Let $C$ be any curve connecting $a$ and $b$, then
  $
    integral_C "d"z = b - a.
  $
  - Let $C$ be any curve connecting $a$ and $b$, then
  $
    integral_C z "d"z = (b^2 - a^2)/2.
  $
  - Let $C$ be a circle centered at the origin with radius $r$ and let $n in bb(C)$, then
  $
    integral_C 1/(z-a)^n "d"z = cases(
      0 & n != -1,
      2 pi"i" & n = -1
    )
  $
]

== Contour Integrals // 围道积分

== Path Independence // 路径无关性

= Cauchy's Theorem and Integral Formula // 柯西定理与积分公式

== Cauchy-Goursat Theorem // 柯西-古尔萨定理

#theorem(name: "Cauchy-Goursat Theorem")[
  If $f(z)$ is analytic in a simply connected domain $D$ and $C$ is a simple closed curve in $D$, then
  $
    integral_C f(z) "d"z = 0.
  $
]

== Cauchy Integral Formula // 柯西积分公式
#theorem(name: "Cauchy Integral Formula")[
  If $f(z)$ is analytic in a simply connected domain $D$ and continuous on $partial D$, and
  $C$ is a simple closed curve in $D$ that encloses a point $z_0$ (usually take $partial D$), then
  $
    f(z_0) = 1/(2 pi"i") integral_C f(z)/(z - z_0) "d"z.
  $
]

== Cauchy Integral Formula for Derivatives // 导数的柯西积分公式

== Morera's Theorem // 莫雷拉定理

== Liouville's Theorem // 刘维尔定理

== Fundamental Theorem of Algebra // 代数基本定理

= Applications of Cauchy Integral Formula // 柯西积分公式的应用

== Maximum Modulus Principle // 最大模原理
#theorem(name: "Maximum Modulus Principle")[ // 最大模原理
  Let $f(z)$ be a non-constant analytic function in a bounded region $D subset CC$ that is continuous on the closure of $D$. Then the maximum of $|f(z)|$ on the closure of $D$ is attained on the boundary of $D$.
]

== Mean Value Property // 平均值性质

== Schwarz Lemma // 施瓦茨引理

== Identity Theorem // 恒等定理

== Weierstrass Convergence Theorem // 魏尔斯特拉斯收敛定理

#part("Series") // 级数
= Power Series and Taylor Series // 幂级数和泰勒级数
== Complex Series // 复级数
// 实数级数中, 只依赖距离和完备性的结论都能直接推广到复数级数 (绝对值替换成模); 但依赖序结构和特殊交错形式的结论不能。复数引入模后，许多判别法变得更统一，但条件收敛行为更复杂。
In real analysis, only the results that depend on completeness and distance can be directly extended to complex analysis (absolute value replaced by modulus); but the results that depend on order structure and special interleaving form cannot. After introducing the modulus, many criteria become more uniform, but the conditions of convergent behavior become more complex.

// 下面我们复级数区别于实数级数的部分
In the following, we will focus on the parts where complex series differ from real series.

=== Rearrangement of Series // 级数的重排
// 对于实数级数，条件收敛的级数可通过重排收敛到任意实数。
// 对于复数级数，情况更复杂（因为条件收敛的实部和虚部各自可能条件收敛），但绝对收敛的复数级数可以任意重排而不改变和，这和实数完全一样。
For real series, conditionally convergent series can be rearranged to converge to any real number.

For complex series, the situation is more complicated (because the real and imaginary parts of a conditionally convergent series may each be conditionally convergent), but absolutely convergent complex series can be rearranged arbitrarily without changing the sum, which is exactly the same as for real series.


== Radius of Convergence and Properties of Power Series // 收敛半径与幂级数的性质

=== Abel's Theorem for Power Series // 幂级数的阿贝尔定理

== Taylor Series

#theorem(name: "Taylor's Theorem")[
  Let $f(z)$ be holomorphic in region $D subset CC$ and $z_0 in D$. Then there exists the unique power series expansion of $f$ at $z_0$:
  $
    f(z) = sum_(n=0)^infinity c_n (z - z_0)^n,
  $
  where
  $
    c_n = 1/(2 pi "i") integral_(|z-z_0|=r) f(z)/(z-z_0)^(n+1) dif z = f^(n)(z_0)/n!,
  $
  and the radius of convergence of this power series is at least the distance from $z_0$ to the boundary of $D$.
]

== Isolation and Uniqueness of Zeros of Analytic Functions // 解析函数零点孤立性与唯一性
#definition(name: "m-th Order Zero")[ // m阶零点
  Let $f(z)$ be analytic in region $D subset CC$ and $z_0 in D$. We say that $z_0$ is an $m$-th order zero of $f$ if
  $
    f(z_0) = f'(z_0) = ... = f^(m-1)(z_0) = 0, quad f^(m)(z_0) != 0.
  $
]

#theorem[
  The point $z_0$ is an $m$-th order zero of the analytic function $f(z)$ that is not identically zero if and only if
  $
    f(z) = (z - z_0)^m g(z),
  $
  where $g(z)$ is analytic in a neighborhood of $z_0$ and $g(z_0) != 0$.
]

#theorem(name: "Isolation of Zeros")[
  Let $f(z)$ be an analytic function in region $D subset CC$ that is not identically zero. Then the zeros of $f$ are isolated, i.e., for each zero $z_0$ of $f$, there exists a neighborhood of $z_0$ that contains no other zeros of $f$.
]

#theorem(name: "Uniqueness of Zeros")[
  Let $f_1(z), f_2(z)$ be analytic functions in region $D subset CC$ that are not identically zero.
  There is a sequence ${z_n} (z!=z_0)$ that is converging to $z_0$ such that $f_1(z_n) = f_2(z_n) = 0$ for all $n$.
  Then $f_1(z) equiv f_2(z)$ for all $z in D$.
]

= Laurent Series // 洛朗级数
== Two-Sided Power Series and Laurent's Theorem // 双向幂级数与洛朗定理
Considering two series:
$
  c_0 + c_1 (z-z_0) + c_2 (z-z_0)^2 + ..., \
  c_{-1}/(z-z_0) + c_{-2}/(z-z_0)^2 + dots .
$
The first one is a power series, which stands for an analytic function $f_1(z)$ in a convergent disk $|z-z_0| < R (0<R<=infinity)$.
As for the second one, let $zeta = 1/(z-z_0)$, then it becomes a power series in $zeta$:
$
  c_{-1} zeta + c_{-2} zeta^2 + dots,
$
which stands for an analytic function $f_2(zeta)$ in a convergent disk $|zeta| < 1/r (0< 1/r <= infinity)$.
That is, the second series stands for an analytic function $f_2(z)$ in the region $|z-z_0| > r (0<r<=infinity)$.
If there exists a non-empty annulus $r < |z-z_0| < R$, then the sum of the two series, called a two-sided power series, denoted as



#eq[
  $
    sum_(n=-infinity)^infinity c_n (z-z_0)^n.
  $
] <two-sided-power-series>

#property[
  Let the convergent disk of series @two-sided-power-series be
  $
    H: r < |z-z_0| < R (0<=r<R<=infinity).
  $
  Then:
  + @two-sided-power-series absolutely converges and internally closed uniformly converges to $f(z) = f_1(z) + f_2(z)$ in $H$.
  + $f(z)$ is analytic in $H$ .
  + $f(z) = sum_(n=-infinity)^infinity c_n (z-z_0)^n$ in H can be termwise differentiated $p$ times.  // 函数在 H 内可以逐项求导 p 次
  + $f(z)$ can be integrated along any path in $H$, and the integral equals the sum of the integrals of the terms.
]

#theorem(name: "Laurent's Theorem")[
  Let $f(z)$ is analytic in the annulus $H: r < |z-z_0| < R (0<=r<R<=infinity)$.
  Then $f(z)$ can be represented as a two-sided power series:
  $
    f(z) = sum_(n=-infinity)^infinity c_n (z-z_0)^n,
  $
  where
  $
    c_n = 1/(2 pi"i") integral_(|z-z_0|=rho) f(z)/(z-z_0)^(n+1) dif z, quad r < rho < R, n = 0, plus.minus 1, plus.minus 2, ...
  $
]

== Classification of Singularities // 奇点的分类
#theorem(name: "Isolated Singularities")[
  Let $f(z)$ be an analytic function in the punctured disk $0 < |z-z_0| < R (0<R<=infinity)$.
  Then $z_0$ is called an isolated singularity of $f$.
]

If $z_0$ is an isolated singularity of $f$, then $f(z)$ can be represented as a Laurent series in the annulus $0 < |z-z_0| < R$.
There are two common methods to expand $f(z)$ into a Laurent series:
+ Method 1: Directly compute the coefficients $c_n$ using the integral formula.
+ Method 2: According to the uniqueness of the series composed of positive and negative power terms, use algebraic calculations, variable substitution, and Taylor expansion to obtain the Laurent series expansion. // 根据正负幂项组成的级数的唯一性, 使用代数计算、变量代换，并利用泰勒展开去求得洛朗展开式。

Let the Laurent series expansion of $f(z)$ at $z_0$ be
$
  f(z) = sum_(n=-infinity)^infinity c_n (z-z_0)^n.
$
Then we called non-minus power terms $c_n (z-z_0)^n$ the regular part of $f(z)$ at $z_0$, and the minus power terms $c_(-n) (z-z_0)^(-n)$ the principal part of $f(z)$ at $z_0$. Then we can classify the isolated singularity $z_0$ of $f(z)$ as follows:
+ If the principal part of $f(z)$ at $z_0$ is identically zero, i.e., $c_n = 0$ for all $n < 0$, then $z_0$ is called a removable singularity of $f(z)$.
+ If the principal part of $f(z)$ at $z_0$ has only finitely many non-zero terms, i.e., there exists a positive integer $m$ such that $c_n = 0$ for all $n < -m$, then $z_0$ is called a pole of order $m$ of $f(z)$.
+ If the principal part of $f(z)$ at $z_0$ has infinitely many non-zero terms, i.e., $c_n != 0$ for infinitely many negative integers $n$, then $z_0$ is called an essential singularity of $f(z)$.

= Residue Theory // 留数理论

== Residues and Their Calculation // 留数及其计算

== Residue Theorem // 留数定理

== Argument Principle // 辐角原理

== Rouché's Theorem // 儒歇定理

= Evaluation of Real Integrals // 实积分的计算

== Integrals of Rational Functions // 有理函数的积分

== Integrals Involving Trigonometric Functions // 含三角函数的积分

== Improper Integrals // 反常积分

== Integrals with Branch Cuts // 含割线的积分

== Summation of Series // 级数求和

#part("Conformal Mapping and Analytic Continuation") // 共形映射与解析延拓
= Theory of Conformal Mapping // 共形映射理论

= Elementary Conformal Mappings // 初等共形映射

= Analytic Continuation // 解析延拓

#part("Special Functions") // 特殊函数

= Gamma and Beta Functions // 伽马函数与贝塔函数

= Zeta Function and Prime Numbers // ζ函数与素数

= Elliptic Functions // 椭圆函数

#part("Advanced Topics") // 进阶主题

= Entire and Meromorphic Functions // 整函数与亚纯函数

= Harmonic Functions and Dirichlet Problem // 调和函数与狄利克雷问题

= Asymptotic Methods // 渐近方法



#bibliography("references.bib")

// 目录

// --- Part I: Basic Complex Analysis (基础复分析) ---

// Chapter 1: Complex Numbers and the Complex Plane (复数与复平面)
//   Section 1.1: Complex Numbers and Their Geometric Representation (复数与其几何表示)
//   Section 1.2: Polar Form and Euler's Formula (极坐标形式与欧拉公式)
//   Section 1.3: Powers and Roots of Complex Numbers (复数的幂与根)
//   Section 1.4: The Extended Complex Plane (扩充复平面)
//   Section 1.5: Topology of the Complex Plane (复平面的拓扑)

// Chapter 2: Complex Functions (复函数)
//   Section 2.1: Definition and Basic Properties (定义与基本性质)
//   Section 2.2: Limits and Continuity (极限与连续性)
//   Section 2.3: Differentiability and Cauchy-Riemann Equations (可微性与柯西-黎曼方程)
//   Section 2.4: Holomorphic and Analytic Functions (全纯函数与解析函数)
//   Section 2.5: Harmonic Functions (调和函数)

// Chapter 3: Elementary Functions (初等函数)
//   Section 3.1: Exponential Function (指数函数)
//   Section 3.2: Trigonometric and Hyperbolic Functions (三角函数与双曲函数)
//   Section 3.3: Logarithmic Function (对数函数)
//   Section 3.4: Complex Powers (复数幂)
//   Section 3.5: Inverse Trigonometric Functions (反三角函数)

// --- Part II: Complex Integration (复积分) ---

// Chapter 4: Complex Integral (复积分)
//   Section 4.1: Definition and Properties of Complex Integral (复积分的定义与性质)
//   Section 4.2: Contour Integrals (围道积分)
//   Section 4.3: Path Independence (路径无关性)

// Chapter 5: Cauchy's Theorem and Integral Formula (柯西定理与积分公式)
//   Section 5.1: Cauchy-Goursat Theorem (柯西-古尔萨定理)
//   Section 5.2: Cauchy Integral Formula (柯西积分公式)
//   Section 5.3: Cauchy Integral Formula for Derivatives (导数的柯西积分公式)
//   Section 5.4: Morera's Theorem (莫雷拉定理)
//   Section 5.5: Liouville's Theorem (刘维尔定理)
//   Section 5.6: Fundamental Theorem of Algebra (代数基本定理)

// Chapter 6: Applications of Cauchy Integral Formula (柯西积分公式的应用)
//   Section 6.1: Maximum Modulus Principle (最大模原理)
//   Section 6.2: Mean Value Property (平均值性质)
//   Section 6.3: Schwarz Lemma (施瓦茨引理)
//   Section 6.4: Identity Theorem (恒等定理)
//   Section 6.5: Weierstrass Convergence Theorem (魏尔斯特拉斯收敛定理)

// --- Part III: Series (级数) ---

// Chapter 7: Power Series and Taylor Series (幂级数和泰勒级数)
//   Section 7.1: Complex Series (复级数)
//   Section 7.2: Radius of Convergence and Properties of Power Series (收敛半径与幂级数的性质)
//   Section 7.3: Taylor Series (泰勒级数)
//   Section 7.4: Isolation and Uniqueness of Zeros of Analytic Functions (解析函数零点孤立性与唯一性)

// Chapter 8: Laurent Series (洛朗级数)
//   Section 8.1: Two-Sided Power Series and Laurent's Theorem (双向幂级数与洛朗定理)
//   Section 8.2: Classification of Singularities (奇点的分类)

// Chapter 9: Residue Theory (留数理论)
//   Section 9.1: Residues and Their Calculation (留数及其计算)
//   Section 9.2: Residue Theorem (留数定理)
//   Section 9.3: Argument Principle (辐角原理)
//   Section 9.4: Rouché's Theorem (儒歇定理)

// Chapter 10: Evaluation of Real Integrals (实积分的计算)
//   Section 10.1: Integrals of Rational Functions (有理函数的积分)
//   Section 10.2: Integrals Involving Trigonometric Functions (含三角函数的积分)
//   Section 10.3: Improper Integrals (反常积分)
//   Section 10.4: Integrals with Branch Cuts (含割线的积分)
//   Section 10.5: Summation of Series (级数求和)

// --- Part IV: Conformal Mapping and Analytic Continuation (共形映射与解析延拓) ---

// Chapter 11: Theory of Conformal Mapping (共形映射理论)
//   Section 11.1: Conformal Mapping and Analytic Functions (共形映射与解析函数)
//   Section 11.2: Local Properties of Analytic Functions (解析函数的局部性质)
//   Section 11.3: Riemann Mapping Theorem (黎曼映射定理)
//   Section 11.4: Boundary Behavior (边界行为)
//   Section 11.5: Schwarz-Christoffel Transformation (施瓦茨-克里斯托费尔变换)

// Chapter 12: Elementary Conformal Mappings (初等共形映射)
//   Section 12.1: Linear Fractional Transformations (线性分式变换)
//   Section 12.2: Mappings to Canonical Domains (到标准区域的映射)
//   Section 12.3: Mappings of the Unit Disk (单位圆盘的映射)
//   Section 12.4: Mappings of the Upper Half-Plane (上半平面的映射)
//   Section 12.5: Applications to Potential Theory (在势论中的应用)

// Chapter 13: Analytic Continuation (解析延拓)
//   Section 13.1: Direct Analytic Continuation (直接解析延拓)
//   Section 13.2: Analytic Continuation along a Curve (沿曲线的解析延拓)
//   Section 13.3: Monodromy Theorem (单值性定理)
//   Section 13.4: Branch Points and Branch Cuts (支点与割线)
//   Section 13.5: Riemann Surfaces (黎曼曲面)
//   Section 13.6: Schwarz Reflection Principle (施瓦茨反射原理)

// --- Part V: Special Functions (特殊函数) ---

// Chapter 14: Gamma and Beta Functions (伽马函数与贝塔函数)
//   Section 14.1: Gamma Function (伽马函数)
//   Section 14.2: Properties of Gamma Function (伽马函数的性质)
//   Section 14.3: Beta Function (贝塔函数)
//   Section 14.4: Relation between Gamma and Beta Functions (伽马函数与贝塔函数的关系)
//   Section 14.5: Stirling's Formula (斯特林公式)

// Chapter 15: Zeta Function and Prime Numbers (ζ函数与素数)
//   Section 15.1: Riemann Zeta Function (黎曼ζ函数)
//   Section 15.2: Euler Product Formula (欧拉乘积公式)
//   Section 15.3: Functional Equation (函数方程)
//   Section 15.4: Riemann Hypothesis (黎曼猜想)
//   Section 15.5: Prime Number Theorem (素数定理)

// Chapter 16: Elliptic Functions (椭圆函数)
//   Section 16.1: Doubly Periodic Functions (双周期函数)
//   Section 16.2: Weierstrass ℘-Function (魏尔斯特拉斯℘函数)
//   Section 16.3: Jacobi Elliptic Functions (雅可比椭圆函数)
//   Section 16.4: Elliptic Integrals (椭圆积分)
//   Section 16.5: Applications (应用)

// --- Part VI: Advanced Topics (进阶主题) ---

// Chapter 17: Entire and Meromorphic Functions (整函数与亚纯函数)
//   Section 17.1: Weierstrass Factorization Theorem (魏尔斯特拉斯分解定理)
//   Section 17.2: Hadamard Factorization Theorem (阿达马分解定理)
//   Section 17.3: Order and Type of Entire Functions (整函数的阶与型)
//   Section 17.4: Mittag-Leffler Theorem (米塔格-莱夫勒定理)
//   Section 17.5: Picard's Theorems (皮卡定理)

// Chapter 18: Harmonic Functions and Dirichlet Problem (调和函数与狄利克雷问题)
//   Section 18.1: Harmonic Functions in the Plane (平面上的调和函数)
//   Section 18.2: Mean Value Property and Maximum Principle (平均值性质与最大值原理)
//   Section 18.3: Poisson Integral Formula (泊松积分公式)
//   Section 18.4: Dirichlet Problem for the Unit Disk (单位圆盘上的狄利克雷问题)
//   Section 18.5: Dirichlet Problem for General Domains (一般区域上的狄利克雷问题)

// Chapter 19: Asymptotic Methods (渐近方法)
//   Section 19.1: Method of Steepest Descent (最速下降法)
//   Section 19.2: Saddle Point Method (鞍点法)
//   Section 19.3: Watson's Lemma (沃森引理)
//   Section 19.4: Laplace's Method (拉普拉斯方法)
//   Section 19.5: Applications to Special Functions (在特殊函数中的应用)

// 结构说明：
// 本目录分为六个部分，共19章。Part I 建立复分析基础，从复数与复平面到复函数与初等函数；Part II 系统阐述复积分理论，包括复积分的定义、柯西定理与积分公式及其应用；Part III 讨论级数表示，涵盖幂级数、泰勒级数、洛朗级数、留数理论与实积分计算；Part IV 研究共形映射理论及其应用与解析延拓；Part V 介绍伽马函数、ζ函数与椭圆函数等特殊函数；Part VI 涵盖整函数、调和函数与渐近方法等进阶主题。整体编排遵循从基础到应用、从局部到整体、从经典到现代的逻辑主线。
