#import "../../TypstTemplate/math-notes.typ": *

#set document(
  title: "Analyse Complexe",
  author: "Violet",
  date: datetime.today(),
)

#show: apply-style

// --------------------------------------------------------------------------
// Cover + Outline
// --------------------------------------------------------------------------

#make-cover(
  "Analyse Complexe",
  "Violet",
  subtitle: "A notebook for complex analysis",
  institute: "Notiz Mathematiques",
  date: datetime.today().display(),
  version: "v0.2.0",
  extra-info: "This is a notebook for complex analysis.",
)

#make-outline(depth: 2, title: "Contents")


#part("Basic Complex Analysis") // 基础复分析
= Complex Numbers and the Complex Plane // 复数与复平面
== Complex Numbers and Their Geometric Representation // 复数与其几何表示
The numbers with the form $z = x + y"i"$, where $x, y in bb(R)$ and $"i"$ is the imaginary unit satisfying $"i"^2 = -1$, are called *complex numbers*.
$x, y$ are called the real and imaginary parts of $z$ with the notation $x = Re(z)$ ($RR(z)$)
and $y = Im(z)$ ($II(z)$), respectively.
When $y = 0$, $z$ is called a *real number*, and when $x = 0$, $z$ is called a *pure imaginary number*.

Complex numbers can be represented as points in the Cartesian coordinate system
(*complex plane*, also known as the Argand plane, see @fig:complex_plane),
where the horizontal axis (the real axis) represents the real part and
the vertical axis (the imaginary axis) represents the imaginary part.

#figure(
  image("./img/Complex_conjugate_picture.svg.png", width: 25%),
  caption: [Complex number $z$ and its conjugate $overline(z)$ in the complex plane.],
  placement: auto,
  supplement: [Fig.],
) <fig:complex_plane>

$overline(z) = x - y"i"$ is called the *complex conjugate* of $z$.
It is easy to verify the following properties of complex conjugation:

1. $overline(overline(z)) = z, quad overline(z_1 plus.minus z_2) = overline(z_1) plus.minus overline(z_2)$;
2. $overline(z_1 z_2) = overline(z_1) dot overline(z_2), quad overline(z_1 slash z_2) = overline(z_1) slash overline(z_2)$;
3. $z^2 = z overline(z), quad Re(z) = (z + overline(z)) / 2, quad Im(z) = (z - overline(z)) / (2"i")$;
4. $overline(R(a, b, c, dots)) = R(overline(a), overline(b), overline(c), dots)$, where $R$ is any rational function of its arguments.

The set of all complex numbers is denoted by $bb(C)$.

#v(0.7cm)
*Field* is a set $bb(F)$ equipped with two operations (addition and multiplication) that satisfy:

1. $(bb(F), +)$ is an abelian group.
2. $(bb(F) backslash {0}, dot)$ is an abelian group.
3. Multiplication is distributive over addition.

If we define addition and multiplication of complex numbers as follows:

$ (x_1 + y_1"i") + (x_2 + y_2"i") = (x_1 + x_2) + (y_1 + y_2)"i", $

$ (x_1 + y_1"i") dot (x_2 + y_2"i") = (x_1 x_2 - y_1 y_2) + (x_1 y_2 + x_2 y_1)"i", $

then $bb(C)$ forms a field,
which is a quadratic extension of the real numbers and an algebraically closed field of characteristic zero.

Now we give several rigorous definitions of the complex number field for subsequent analysis.

#definition(name: "Complex Number")[
  1. *Analytic/Ordered Pair Definition.* Let
  $
    bb(C) = {(x, y) \| x, y in bb(R)},
  $
  and define addition and multiplication as follows:
  $ (x_1, y_1) + (x_2, y_2) = (x_1 + x_2, y_1 + y_2), $
  $ (x_1, y_1) dot (x_2, y_2) = (x_1 x_2 - y_1 y_2, x_1 y_2 + x_2 y_1). $
  Then $(bb(C), +, dot)$ is a field, called the complex field.
  2. *Polynomial Quotient Ring Definition.* The quotient ring of the polynomial ring $bb(R)[x]$ by the ideal generated by $x^2 + 1$ is a field, denoted by
  $
    bb(C) = (bb(R)[x])/(x^2 + 1),
  $
  called the complex field.
  3. *Matrix Definition.* Let
  $
    bb(C) = {mat(delim: "(", x, -y; y, x) \| x, y in bb(R)}.
  $
  Then $(bb(C), +, dot)$ is a field, where addition and multiplication are defined as matrix addition and multiplication, respectively, called the complex field.
]

Since the field guarantees the existence of multiplicative inverses for non-zero elements,
we can define the division of complex numbers as follows:

$ z^(-1) = 1/z = overline(z)/abs(z)^2 = (x - y"i")/(x^2 + y^2). $

== Polar Form and Euler's Formula // 极坐标形式与欧拉公式

For a non-zero complex number $z = x + y"i"$, the *argument* of $z$,
denoted by $"Arg"(z) = arctan(y/x)$, is defined as
the angle $phi$ between the positive real axis and the line segment from the origin to the point $z$ in the complex plane,
measured in the counterclockwise direction.

It's obvious that a complex number corresponds to infinitely many arguments,
so we usually define the principal value $arg(z)$ to represent the unique argument in the range $(-pi, pi]$.

Moreover, we define the *modulus* of $z$ as $r = abs(z) = sqrt(x^2 + y^2)$,
which is the distance from the origin to the point $z$ in the complex plane.
Then we can express $z$ in polar form as

$ z = r(cos phi + "i" sin phi) = r e^(i phi), $

where $e^(i phi) = cos phi + "i" sin phi$ is known as *Euler's formula*
(refer to @fig:complex_plane).

The polar representation of complex numbers allows us to conveniently perform multiplication and division,
as they correspond to the product and quotient of moduli and the sum and difference of arguments, respectively:

$ z_1 z_2 = r_1 r_2 e^(i (phi_1 + phi_2)), quad z_1 slash z_2 = r_1 slash r_2 e^(i (phi_1 - phi_2)). $

Thus, we know that multiplying two complex numbers is equivalent to multiplying their moduli and adding their arguments, while dividing two complex numbers is equivalent to dividing their moduli and subtracting their arguments.

#note[
  With the help of the polar representation of complex numbers, we can easily prove some trigonometric identities,
  such as the double-angle formulas and the sum and difference formulas.
  For example, using Euler's formula, we have

  $ e^(i 2phi) = (e^(i phi))^2 = (cos phi + "i" sin phi)^2 = cos 2phi + "i" sin 2phi, $

  which gives us the double-angle formulas:

  $ cos 2phi = 2cos^2 phi - 1, quad sin 2phi = 2sin phi cos phi. $

  Similarly, we can derive the sum and difference formulas for sine and cosine.
]

#note[
  With the help of the polar representation of complex numbers, we can rewrite the real matrix definition of the complex field
  to better understand the geometric meaning of complex numbers:

  Let
  $
    bb(C) = mat(delim: "(", r cos phi, -r sin phi; r sin phi, r cos phi) \| r >= 0, phi in [0, 2pi) .
  $
  Then we can verify that the addition and multiplication defined as matrix addition and multiplication, respectively, are consistent with the polar representation of complex numbers.

  When the modulus is $1$, this is the rotation matrix in analytic geometry, which represents the rotational effect of complex numbers in the complex plane.
]

== Powers and Roots of Complex Numbers

Let $z = r e^(i phi)$ be a non-zero complex number.
For any integer $n$, we have
$
  z^n = r^n e^(i n phi) = r^n (cos n phi + "i" sin n phi).
$

Then it can be derived that

$
  abs(z^n) = r^n, quad "Arg"(z^n) = n phi.
$

When $r = 1$, it is called *De Moivre's formula*:

$ (cos phi + "i" sin phi)^n = cos n phi + "i" sin n phi. $

Find the $n$-th roots of $z$ is equivalent to solving the equation $omega^n = z$,
which has $n$ distinct solutions given by

$
  omega_k = r^(1/n) e^(i ((phi + 2k pi)/n)) = r^(1/n) [cos ((phi + 2k pi)/n) + "i" sin ((phi + 2k pi)/n)], quad k = 0, 1, ..., n-1.
$

== The Extended Complex Plane

The *extended complex plane*, denoted by $hat(bb(C))$, is defined as the union of the complex plane $bb(C)$ and the point at infinity $infinity$:

$
  hat(bb(C)) = bb(C) union {infinity}.
$

This extension allows us to treat infinity as a point in the complex plane,
which is particularly useful in complex analysis for
studying the behavior of functions at infinity and for compactifying the complex plane.

The extended complex plane can be visualized as a sphere, called the *Riemann sphere*,
where the point at infinity corresponds to the north pole of the sphere.

#figure(
  image("./img/extended_complex_plane.png", width: 40%),
  caption: [The extended complex plane, also known as the Riemann sphere.],
  placement: auto,
  supplement: [Fig.],
) <fig:extended_complex_plane>

In the extended complex plane, every line intersects at the point at infinity,
so we can view the extended complex plane as a compactification of the complex plane.
This compactification allows us to apply topological and geometric methods to study complex functions,
especially those that have singularities or poles at infinity.

== Topology of the Complex Plane // 复平面的拓扑

= Complex Functions // 复函数

== Definition and Basic Properties // 定义与基本性质

In the previous chapter we studied the algebraic and topological structure of the complex plane $bb(C)$. We now turn our attention to *functions* defined on subsets of $bb(C)$, which form the central object of study in complex analysis.

#definition(name: "Complex Function")[
  A *complex function* is a mapping
  $
    f: E -> bb(C),
  $
  where $E subset bb(C)$ is the *domain* of $f$ (the set on which $f$ is defined). For each $z in E$, the uniquely assigned value $omega = f(z)$ is called the *value* of $f$ at $z$.

  A complex function is called *single-valued* if for every $z in E$ there is exactly one $omega in bb(C)$ such that $f(z) = omega$. Otherwise it is called *multi-valued*.
] <def:complex-function>

#caution(title: "Multi-Valued Functions Are Not True Functions")[
  A so-called multi-valued function is _not a function in the strict set-theoretic sense_, since it violates the uniqueness requirement of the function definition. Nonetheless, we habitually refer to such objects as "functions" for convenience of discussion. Later (in the chapters on elementary functions and analytic continuation) we will use branch cuts and the monodromy theorem to extract single-valued branches from multi-valued functions.
]

The most fundamental technique in complex analysis is to decompose a complex function into a pair of real-valued functions of two real variables. Write $z = x + y"i"$ with $x, y in bb(R)$. Then every complex function $f$ can be written uniquely as
#eq[$
  f(z) = u(x, y) + "i" v(x, y),
$] <eq:re-im-decomp>
where $u, v: E subset bb(R)^2 -> bb(R)$ are real-valued functions. We call $u = Re(f)$ the *real part* and $v = Im(f)$ the *imaginary part* of $f$. This decomposition is the primary bridge between complex analysis and multivariable real analysis, and will be used constantly throughout these notes.

#note[
  The decomposition @eq:re-im-decomp turns a single complex-valued function of one complex variable into a pair of real-valued functions of two real variables. This correspondence will allow us to import results from the calculus of two variables _when appropriate_, but we will also see that the extra structure imposed by complex differentiability (the Cauchy-Riemann equations) makes complex functions far more rigid than arbitrary pairs of real functions.
]

A complex function $f: E -> bb(C)$ can be interpreted geometrically as a mapping from its domain $E$ (a subset of the *$z$-plane*) onto its image $f(E)$ (a subset of the *$w$-plane*). Unlike a graph in $bb(R)^2$, the graph of a complex function would require four real dimensions, so instead one visualizes $f$ as a transformation that moves points, curves, and regions from the source plane to the target plane.

#figure(
  image("./img/Complex_conjugate_picture.svg.png", width: 30%),
  caption: [A complex function $f: bb(C) -> bb(C)$ can be visualized as a transformation between two copies of the complex plane, the $z$-plane and the $w$-plane. Shown here: the mapping $w = overline(z)$ reflects across the real axis.],
  placement: auto,
  supplement: [Fig.],
) <fig:z-w-mapping>

#definition(name: "Bounded Complex Function")[
  A complex function $f: E -> bb(C)$ is *bounded* on $E$ if there exists a constant $M >= 0$ such that
  $
    |f(z)| <= M quad "for all" z in E.
  $
]

Given two functions $f: E -> bb(C)$ and $g: F -> bb(C)$ with $f(E) subset F$, their *composition* $g compose f: E -> bb(C)$ is defined by
$
  (g compose f)(z) = g(f(z)).
$
In terms of the real and imaginary parts, if $f(z) = u_1 + "i"v_1$ and $g(w) = u_2 + "i"v_2$, then the real and imaginary parts of $g compose f$ are obtained by substituting $w = f(z)$ into $g$, i.e., $u_2(u_1, v_1)$ and $v_2(u_1, v_1)$.

== Limits and Continuity // 极限与连续性

#definition(name: "Limit of a Complex Function")[
  Let $f: E -> bb(C)$ be a complex function and let $z_0 in bb(C)$ be an accumulation point of $E$. We say that $f(z)$ tends to the *limit* $omega_0 in bb(C)$ as $z$ approaches $z_0$, written
  $
    lim_(z -> z_0) f(z) = omega_0,
  $
  if for every $epsilon > 0$ there exists $delta > 0$ such that
  $
    0 < |z - z_0| < delta text(" and ") z in E quad => quad |f(z) - omega_0| < epsilon.
  $
] <def:complex-limit>

The limit of a complex function can be completely characterized by the limits of its real and imaginary parts, which reduces the study of complex limits to that of real bivariate limits.

#theorem(name: "Limit via Real and Imaginary Parts")[
  Let $f(z) = u(x, y) + "i"v(x, y)$ and $omega_0 = a + "i"b$. Then
  $
    lim_(z -> z_0) f(z) = omega_0
  $
  if and only if
  $
    lim_((x,y) -> (x_0, y_0)) u(x, y) = a quad text(" and ") quad lim_((x,y) -> (x_0, y_0)) v(x, y) = b.
  $
] <thm:limit-real-image>

#proof[
  The inequalities
  $
    |u - a| <= |f - omega_0| <= |u - a| + |v - b|,
    quad
    |v - b| <= |f - omega_0| <= |u - a| + |v - b|
  $
  show that $|f - omega_0|$ is small if and only if both $|u - a|$ and $|v - b|$ are small. The $epsilon$-$delta$ definitions are therefore equivalent.
]

#property(name: "Elementary Properties of Limits")[
  Assume $lim_(z -> z_0) f(z) = alpha$ and $lim_(z -> z_0) g(z) = beta$. Then:
  - *Uniqueness*: The limit, if it exists, is unique.
  - *Linearity*: $lim_(z -> z_0) (lambda f(z) + mu g(z)) = lambda alpha + mu beta$ for all $lambda, mu in bb(C)$.
  - *Product*: $lim_(z -> z_0) (f(z) g(z)) = alpha beta$.
  - *Quotient*: $lim_(z -> z_0) (f(z) / g(z)) = alpha / beta$, provided $beta != 0$.
  - *Composition*: If $lim_(w -> alpha) h(w) = gamma$ and $h$ is continuous at $alpha$ (or if $f(z) != alpha$ near $z_0$), then $lim_(z -> z_0) h(f(z)) = gamma$.
  - *Squeeze*: If $|f(z)| <= g(z)$ for all $z$ near $z_0$ and $lim_(z -> z_0) g(z) = 0$, then $lim_(z -> z_0) f(z) = 0$.
]

#note[
  The proofs of the properties in #link(<thm:limit-real-image>)[Limit via Real and Imaginary Parts] and the above list are formally identical to their real-variable counterparts: simply replace every occurrence of the real absolute value with the complex modulus. For this reason we do not repeat the details here, and refer the reader to any standard textbook on multivariable real calculus.
]

We also extend the definition of limit to include the point at infinity from the extended complex plane $hat(bb(C))$ (see §1.4).

- We write $lim_(z -> z_0) f(z) = oo$ if for every $M > 0$ there exists $delta > 0$ such that $0 < |z - z_0| < delta$ implies $|f(z)| > M$.
- We write $lim_(z -> oo) f(z) = omega_0$ if for every $epsilon > 0$ there exists $R > 0$ such that $|z| > R$ implies $|f(z) - omega_0| < epsilon$.

We now turn to continuity.

#definition(name: "Continuity of a Complex Function")[
  A complex function $f: E -> bb(C)$ is *continuous at a point* $z_0 in E$ if
  $
    lim_(z -> z_0) f(z) = f(z_0).
  $
  If $f$ is continuous at every point of $E$, we say that $f$ is *continuous on $E$*.
]

#definition(name: "Uniform Continuity")[
  A function $f: E -> bb(C)$ is *uniformly continuous* on $E$ if for every $epsilon > 0$ there exists $delta > 0$ such that
  $
    z_1, z_2 in E text(" and ") |z_1 - z_2| < delta quad => quad |f(z_1) - f(z_2)| < epsilon.
  $
]

#proposition(name: "Equivalent Characterizations of Continuity")[
  Let $f: E -> bb(C)$ have real and imaginary parts $u, v$. The following are equivalent:
  1. $f$ is continuous at $z_0 in E$.
  2. $u$ and $v$ are both continuous at $(x_0, y_0)$ (as functions from $bb(R)^2$ to $bb(R)$).
  3. For every sequence $(z_n)_(n in bb(N)) subset E$ with $z_n -> z_0$, one has $f(z_n) -> f(z_0)$.
]

#property(name: "Algebra of Continuous Functions")[
  If $f$ and $g$ are continuous on $E$, then so are $f +- g$, $f dot g$, and (where $g(z) != 0$) $f / g$. If $g$ is continuous on $f(E)$ and $f$ is continuous on $E$, then the composition $g compose f$ is continuous on $E$.
]

Continuous functions on compact sets enjoy particularly strong properties, which we will use repeatedly in later chapters.

#theorem(name: "Continuous Functions on Compact Sets")[
  Let $K subset bb(C)$ be compact (closed and bounded) and let $f: K -> bb(C)$ be continuous on $K$. Then:
  1. *Boundedness*: $f$ is bounded on $K$, i.e., $sup_(z in K) |f(z)| < oo$.
  2. *Extremal values*: There exist points $z_max, z_min in K$ such that
    $
      |f(z_max)| = sup_(z in K) |f(z)|, quad |f(z_min)| = inf_(z in K) |f(z)|.
    $
  3. *Uniform continuity*: $f$ is uniformly continuous on $K$.
] <thm:compact-continuous>

#proof[
  Claims (1) and (3) are direct consequences of the Heine-Borel and Heine-Cantor theorems in the Euclidean metric space $bb(R)^2$, applied separately to the real and imaginary parts. Claim (2) follows from the fact that the modulus $|f|$ is a continuous real-valued function on the compact set $K$, and a continuous real function on a compact set attains its supremum and infimum.
]

#example(name: "A Function with No Limit at the Origin")[
  Define $f: bb(C) backslash {0} -> bb(C)$ by $f(z) = z / |z|$. Restricting to the ray $z = r e^(i theta)$ (with $theta$ fixed and $r -> 0^+$), we get
  $
    f(r e^(i theta)) = (r e^(i theta)) / r = e^(i theta).
  $
  Thus $f$ approaches a different value for each direction $theta$: it tends to $1$ along the positive real axis, $-1$ along the negative real axis, $"i"$ along the positive imaginary axis, and so on. Therefore $lim_(z -> 0) f(z)$ does not exist, even though $|f(z)| = 1$ for all $z != 0$.
]

#caution(title: "Continuity of $f$ vs. Continuity of $|f|$")[
  It follows from the triangle inequality that if $f$ is continuous at $z_0$, then so is the real-valued function $|f|$. The converse is false: the function $f(z) = z / |z|$ of the preceding example has $|f(z)| = 1$ (hence $|f|$ is continuous everywhere on $bb(C) backslash {0}$), but $f$ itself does not have a limit at $0$, so it cannot be extended to a continuous function on $bb(C)$.

  In a different spirit, $f(z) = e^(i / z)$ has $|f(z)| = 1$ for all $z != 0$, yet it has no limit as $z -> 0$ along the imaginary axis.
]

== Differentiability and Analytic Functions // 可微性与解析函数

We are now ready to introduce the concept that truly distinguishes complex analysis from the real analysis of two variables: complex differentiability.

#definition(name: "Derivative and Differential")[
  Let $f: E -> bb(C)$ be a complex function and let $z_0 in E$ be an interior point of $E$. The function $f$ is *derivable* (or *differentiable*) at $z_0$ if the limit
  #eq[$
    f'(z_0) = lim_(z -> z_0) frac(f(z) - f(z_0), z - z_0)
  $] <eq:complex-derivative>
  exists as a finite complex number. The value $f'(z_0)$ is called the *derivative* of $f$ at $z_0$.

  The *differential* of $f$ at $z_0$ is the linear map $"d"f(z_0): bb(C) -> bb(C)$ defined by
  $
    "d"f(z_0)(Delta z) = f'(z_0) Delta z,
  $
  and one writes $"d"f = f'(z_0) "d"z$.
] <def:complex-diff>

#note[
  For complex functions, _derivability and differentiability are equivalent_, just as in one-variable real calculus. This is in stark contrast to the case of multivariable real functions, where the existence of all partial derivatives does not guarantee (Frechet) differentiability. The reason lies in the rigidity of the difference quotient @eq:complex-derivative, which forces the limit to be independent of the direction from which $z$ approaches $z_0$ — a condition far stronger than mere directional differentiability.
]

Geometrically, multiplication by $f'(z_0)$ sends each infinitesimal vector $"d"z$ to $f'(z_0) "d"z$. Writing $f'(z_0) = R e^(i phi)$ in polar form, this operation consists of a *scaling* by $R = |f'(z_0)|$ followed by a *rotation* by $phi = arg(f'(z_0))$. Thus the differential of a complex-differentiable map is a *conformal* (angle-preserving) infinitesimal transformation: it preserves the angles and the ratio of lengths between any two tangent vectors at $z_0$. This is the geometric source of the theory of conformal mappings, which we study systematically in Part IV.

We now derive the celebrated Cauchy-Riemann equations, which provide the algebraic link between complex differentiability and the partial derivatives of $u$ and $v$.

#theorem(name: "Cauchy-Riemann Equations (Necessity)")[
  Let $f = u + "i"v$ be complex-differentiable at $z_0 = x_0 + "i"y_0$. Then all four first-order partial derivatives
  $
    (partial_x u)(x_0, y_0), quad (partial_y u)(x_0, y_0),
    quad
    (partial_x v)(x_0, y_0), quad (partial_y v)(x_0, y_0)
  $
  exist at $(x_0, y_0)$ and satisfy the *Cauchy-Riemann equations*:
  #eq[$
    cases(
      partial_x u = partial_y v,
      partial_y u = -partial_x v.
    )
  $] <eq:CR-cartesian>

  Moreover, the derivative may be computed from the partials by either of the two formulas:
  $
    f'(z_0) = partial_x u + "i" partial_x v = partial_y v - "i" partial_y u.
  $
] <thm:CR-necessary>

#proof[
  Let $Delta z = Delta x + "i" Delta y$. By assumption the limit in @eq:complex-derivative exists regardless of how $Delta z -> 0$. We evaluate it along two particular paths.

  *Path 1 (along the real axis).* Take $Delta y = 0$ and let $Delta x -> 0$. Then
  $
    frac(f(z_0 + Delta x) - f(z_0), Delta x)
    = frac(u(x_0 + Delta x, y_0) - u(x_0, y_0), Delta x)
    + "i" frac(v(x_0 + Delta x, y_0) - v(x_0, y_0), Delta x)
    -> partial_x u + "i" partial_x v.
  $

  *Path 2 (along the imaginary axis).* Take $Delta x = 0$ and let $Delta y -> 0$. Then
  $
    frac(f(z_0 + "i" Delta y) - f(z_0), "i" Delta y)
    = frac(u(x_0, y_0 + Delta y) - u(x_0, y_0), "i" Delta y)
    + "i" frac(v(x_0, y_0 + Delta y) - v(x_0, y_0), "i" Delta y).
  $
  Using $1/"i" = -"i"$, the right-hand side simplifies to
  $
    -"i" partial_y u + partial_y v = partial_y v - "i" partial_y u.
  $

  Since the two limits must equal $f'(z_0)$, equating their real and imaginary parts yields exactly @eq:CR-cartesian.
]

For problems expressed in polar coordinates it is often more convenient to use the polar form of the Cauchy-Riemann equations.

#proposition(name: "Cauchy-Riemann Equations in Polar Form")[
  Let $z = r e^(i phi)$ and write $f(z) = u(r, phi) + "i"v(r, phi)$. If $f$ is differentiable at a point with $r != 0$, then
  #eq[$
    partial_r u = frac(1, r) partial_phi v, quad partial_r v = -frac(1, r) partial_phi u.
  $] <eq:CR-polar>
  Conversely, if $u, v$ are Frechet-differentiable (as functions of $r, phi$) and satisfy @eq:CR-polar, then $f$ is complex-differentiable.
]

The Cauchy-Riemann equations alone are _not_ sufficient for complex differentiability; one also needs the real and imaginary parts to be Frechet-differentiable as functions on $bb(R)^2$. The correct necessary and sufficient statement is the following.

#theorem(name: "Necessary and Sufficient Condition for Complex Differentiability")[
  Let $f = u + "i"v$ be defined on an open set containing $z_0 = x_0 + "i"y_0$. Then $f$ is complex-differentiable at $z_0$ if and only if:
  1. $u$ and $v$ are (Frechet) differentiable at $(x_0, y_0)$ as functions from $bb(R)^2$ to $bb(R)$;
  2. $u$ and $v$ satisfy the Cauchy-Riemann equations @eq:CR-cartesian at $(x_0, y_0)$.
] <thm:complex-diff-equiv>

#proof[
  *Necessity.* If $f$ is complex-differentiable, then the Cauchy-Riemann equations hold by #link(<thm:CR-necessary>)[Cauchy-Riemann Equations (Necessity)]. Moreover, from @eq:complex-derivative one has
  $
    f(z_0 + Delta z) - f(z_0) = f'(z_0) Delta z + o(|Delta z|).
  $
  Writing this in real and imaginary parts gives the Frechet differentiability of $u$ and $v$, with Jacobian matrix
  $
    mat(delim: "(", partial_x u, partial_y u; partial_x v, partial_y v)
    = mat(delim: "(", Re(f'), -Im(f'); Im(f'), Re(f')).
  $

  *Sufficiency.* If $u, v$ are Frechet-differentiable, then
  $
    Delta u = partial_x u Delta x + partial_y u Delta y + o(sqrt(Delta x^2 + Delta y^2)),
    quad
    Delta v = partial_x v Delta x + partial_y v Delta y + o(sqrt(Delta x^2 + Delta y^2)).
  $
  Using the Cauchy-Riemann equations to substitute $partial_y u = -partial_x v$ and $partial_y v = partial_x u$ into the expression for $Delta f = Delta u + "i" Delta v$, we obtain
  $
    Delta f = (partial_x u + "i" partial_x v)(Delta x + "i" Delta y) + o(|Delta z|),
  $
  which is exactly the statement that $f'(z_0) = partial_x u + "i" partial_x v$ exists.
]

#caution(title: "Partial Derivatives + CR $neq$ Complex Differentiability")[
  It is a common mistake to assume that the mere existence of the four partial derivatives together with the Cauchy-Riemann equations implies complex differentiability. This is false: Frechet differentiability of $(u, v)$ is strictly stronger than the existence of the partial derivatives. A standard counterexample is
  $
    f(0) = 0, quad f(z) = z^5 / |z|^4 text(" for ") z != 0.
  $
  At $z = 0$ one has $partial_x u = partial_y u = partial_x v = partial_y v = 0$, so the Cauchy-Riemann equations are trivially satisfied at the origin; however, approaching $0$ along the ray $z = t(1 + "i")$ with $t -> 0$ yields $f(z)/z -> (1+"i")^5 / 4$, which differs from $0$. Therefore $f'(0)$ does not exist.
]

#property(name: "Algebra of Derivatives")[
  If $f, g$ are differentiable at $z_0$ and $lambda in bb(C)$, then:
  - *Linearity*: $(lambda f + mu g)'(z_0) = lambda f'(z_0) + mu g'(z_0)$.
  - *Product rule*: $(f dot g)'(z_0) = f'(z_0) g(z_0) + f(z_0) g'(z_0)$.
  - *Quotient rule*: $(f / g)'(z_0) = (f'(z_0) g(z_0) - f(z_0) g'(z_0)) / g(z_0)^2$, provided $g(z_0) != 0$.
  - *Chain rule*: If $g$ is differentiable at $f(z_0)$ then $(g compose f)'(z_0) = g'(f(z_0)) dot f'(z_0)$.
  - *Inverse function*: If $f'(z_0) != 0$ then $f^(-1)$ is differentiable at $w_0 = f(z_0)$ and $(f^(-1))'(w_0) = 1 / f'(z_0)$.
]

We now elevate differentiability from a pointwise notion to a regional one. The result is the central class of functions in complex analysis.

#definition(name: "Holomorphic Function")[
  A function $f: E -> bb(C)$ is *holomorphic at a point* $z_0 in E$ if there exists an open neighborhood $U subset E$ of $z_0$ such that $f$ is differentiable at every point of $U$.

  If $f$ is holomorphic at every point of an open set $D subset bb(C)$, we say that $f$ is *holomorphic on $D$*, and we write $f in cal(H)(D)$.
] <def:holomorphic>

A more classical terminology, which keeps consistency with the usage in real analysis, defines analyticity in terms of local power series expansions.

#definition(name: "Analytic Function")[
  A function $f: E -> bb(C)$ is *analytic at a point* $z_0 in E$ if there exists an open neighborhood $U$ of $z_0$ and a sequence of coefficients $(a_n)_(n >= 0) subset bb(C)$ such that for all $z in U$,
  #eq[$
    f(z) = sum_(n=0)^oo a_n (z - z_0)^n.
  $] <eq:power-series-def>

  If $f$ is analytic at every point of an open set $D$, then $f$ is *analytic on $D$*.
] <def:analytic>

It is one of the deepest and most remarkable facts of complex analysis — far from obvious from the definitions — that the two notions above are actually equivalent on open subsets of $bb(C)$.

#theorem(name: "Equivalence of Holomorphy and Analyticity")[
  Let $D subset bb(C)$ be open. A function $f: D -> bb(C)$ is holomorphic on $D$ if and only if it is analytic on $D$.
] <thm:holo-equiv-analytic>

#proof[
  The easy direction (analytic $=>$ holomorphic) follows from the fact that a convergent power series can be differentiated term by term within its radius of convergence, yielding another power series; thus every power series defines a holomorphic function. This will be proved rigorously in §7.2 when we study power series in detail.

  The non-trivial direction (holomorphic $=>$ analytic) is a consequence of the Cauchy integral formula: once one represents a holomorphic function as a contour integral, expanding the integrand as a geometric series yields the required power series representation. We prove this in §7.3 as part of Taylor's theorem for analytic functions.
]

#note(title: "On the Usage of 'Holomorphic' and 'Analytic'")[
  In some textbooks, especially those of a more classical tradition, no distinction is made between _holomorphic_ and _analytic_ functions: the two words are used interchangeably. This is perfectly legitimate in view of #link(<thm:holo-equiv-analytic>)[Equivalence of Holomorphy and Analyticity], since for functions on open subsets of $bb(C)$ the concepts coincide.

  However, the situation is very different for real-valued functions of a real variable: a $C^oo$ real function need _not_ be real-analytic (the classic counterexample $e^(-1/x^2)$ extended by $0$ at the origin is $C^oo$ on $bb(R)$ but not real-analytic at $0$). In order to maintain terminological consistency with real analysis, we define complex analyticity _à priori_ via local power series expansions (@eq:power-series-def) and holomorphic via local differentiability, then prove the equivalence as a substantive theorem. In the rest of these notes we will generally prefer the term *holomorphic* when thinking in terms of differentiation, and *analytic* when thinking in terms of power series.
]

#caution(title: "Pointwise Differentiability vs. Holomorphy at a Point")[
  Holomorphy at a point $z_0$ is a strictly stronger condition than mere differentiability at $z_0$: it requires differentiability throughout some open neighborhood of $z_0$. For example, the function $f(z) = |z|^2 = z overline(z)$ has real and imaginary parts $u = x^2 + y^2$, $v = 0$, whose partial derivatives are continuous everywhere; the Cauchy-Riemann equations reduce to $2x = 0$ and $2y = 0$, which hold _only_ at the origin. Thus $f$ is differentiable at $z = 0$ with $f'(0) = 0$, but it is not differentiable at any other point, so there is no open set around $0$ on which $f$ is differentiable. Therefore $f$ is _not_ holomorphic at $0$.
]

#example(name: "Elementary Holomorphic Functions")[
  - *Constant functions.* If $f(z) = c$ for all $z$, then $f'(z) = 0$ everywhere, so $f in cal(H)(bb(C))$.
  - *Identity.* If $f(z) = z$, then the difference quotient @eq:complex-derivative equals $1$ for any $z$, so $f in cal(H)(bb(C))$ with $f'(z) = 1$.
  - *Polynomials.* By induction using the product rule and linearity, every polynomial
    $
      P(z) = a_n z^n + a_(n-1) z^(n-1) + dots + a_0
    $
    is entire (i.e., holomorphic on all of $bb(C)$), with
    $
      P'(z) = n a_n z^(n-1) + (n-1) a_(n-1) z^(n-2) + dots + a_1.
    $
  - *Rational functions.* A quotient $P(z) / Q(z)$ of two polynomials is holomorphic on the complement of the zero set of $Q$, with derivative given by the quotient rule.
]

#example(name: "Classical Non-Holomorphic Functions")[
  We verify that several simple functions are _nowhere_ holomorphic, using the Cauchy-Riemann equations.
  - *Complex conjugate.* Let $f(z) = overline(z) = x - "i"y$, so $u = x$, $v = -y$. The partials are $partial_x u = 1$, $partial_y v = -1$. Since $1 != -1$, the first CR equation fails at every point, and therefore $f$ is nowhere complex-differentiable.
  - *Real part.* Let $f(z) = Re(z) = x$. Then $u = x$, $v = 0$, so $partial_x u = 1$ but $partial_y v = 0$. Again the CR equations fail everywhere.
  - *Modulus.* Let $f(z) = |z| = sqrt(x^2 + y^2)$. For $z != 0$, direct computation gives $partial_x u = x/|z|$, $partial_y v = 0$, so the first CR equation fails. At $z = 0$ the difference quotient $|z|/z$ has no limit (it equals $e^(-i theta)$ on the ray $z = r e^(i theta)$), confirming that $f$ is nowhere differentiable.
  - *Square of modulus.* $f(z) = |z|^2$, already treated above: differentiable only at $z = 0$, and not holomorphic there.
]

A point at which a function fails to be holomorphic is called a *singular point*, or briefly a *singularity*. Singularities are classified in great detail once the Laurent series machinery is available (Chapter 8): removable singularities, poles of finite order, and essential singularities. For the moment we content ourselves with the intuitive concept.

#note(title: "The Rigidity Phenomenon")[
  Holomorphic functions enjoy a "rigidity" that is entirely foreign to real differentiable functions. We mention three striking illustrations, to be proved in later chapters:
  1. *Infinite differentiability.* Every holomorphic function is automatically $C^oo$ (and, by #link(<thm:holo-equiv-analytic>)[Equivalence of Holomorphy and Analyticity], even real-analytic in both variables).
  2. *Uniqueness / Identity theorem.* If two holomorphic functions on a connected domain $D$ agree on any subset with an accumulation point in $D$, they must be identical on all of $D$. No such property holds for $C^oo$ real functions.
  3. *Maximum modulus principle.* A non-constant holomorphic function on a domain cannot attain a local maximum of its modulus inside the domain — the maximum must lie on the boundary.

  These three properties alone make holomorphic functions far more structured than their real-variable counterparts, and they form the backbone of most applications of complex analysis.
]

== Harmonic Functions // 调和函数

The Cauchy-Riemann equations link the real and imaginary parts of a holomorphic function in a very special way. When we differentiate them once more, a second-order partial differential equation emerges — the Laplace equation. Its solutions are the *harmonic functions*, which occupy a central position at the crossroads of complex analysis, potential theory, and mathematical physics.

#definition(name: "Harmonic Function")[
  Let $D subset bb(R)^2$ be open. A twice continuously differentiable real-valued function $u: D -> bb(R)$ is *harmonic* on $D$ if it satisfies the *Laplace equation*
  #eq[$
    nabla^2 u = (partial_x)^2 u + (partial_y)^2 u = 0
  $] <eq:laplace>
  at every point of $D$. Here $nabla^2 = partial_x^2 + partial_y^2$ is the Laplace operator in two dimensions.
] <def:harmonic>

The next theorem explains why harmonic functions are an integral part of complex analysis.

#theorem(name: "Real and Imaginary Parts of a Holomorphic Function Are Harmonic")[
  Let $f = u + "i"v$ be holomorphic on a domain $D$ and assume that $u, v in C^2(D)$. Then both $u$ and $v$ are harmonic on $D$.
] <thm:analytic-harmonic>

#proof[
  Differentiating the Cauchy-Riemann equations @eq:CR-cartesian:
  $
    partial_x u = partial_y v quad => quad partial_x^2 u = partial_x partial_y v,
  $
  $
    partial_y u = -partial_x v quad => quad partial_y^2 u = -partial_y partial_x v.
  $
  Since $u in C^2(D)$, the mixed partial derivatives of $v$ are equal (Schwarz's theorem), so adding the two displayed lines yields
  $
    nabla^2 u = partial_x^2 u + partial_y^2 u = partial_x partial_y v - partial_y partial_x v = 0.
  $
  The same computation, with the roles of $u$ and $v$ interchanged, shows that $nabla^2 v = 0$ as well.
]

#note[
  The $C^2$ assumption in #link(<thm:analytic-harmonic>)[Real and Imaginary Parts of a Holomorphic Function Are Harmonic] is actually superfluous: a holomorphic function is automatically $C^oo$ (and indeed real-analytic in both variables), as will follow from the Cauchy integral formula in §5.2. We keep the $C^2$ hypothesis here only because our current proof uses equality of mixed partial derivatives.
]

#definition(name: "Conjugate Harmonic Function")[
  Let $u$ be harmonic on a domain $D$. A real-valued function $v$ on $D$ is a *conjugate harmonic function* of $u$ if $u$ and $v$ together satisfy the Cauchy-Riemann equations @eq:CR-cartesian on all of $D$, i.e., if $f = u + "i"v$ is holomorphic on $D$.
]

#caution(title: "Conjugate Relation Is Not Symmetric")[
  If $v$ is a conjugate harmonic of $u$, then $-u$ (not $u$!) is a conjugate harmonic of $v$. Indeed, if $f = u + "i"v$ is holomorphic, then so is $-i f = v - "i"u$; this shows that the conjugate of $v$ is $-u$. Thus the relation "is a conjugate harmonic of" is asymmetric, unlike the statement that $u$ and $v$ are "conjugate harmonic to each other".
]

Given a harmonic function $u$ on a *simply connected* domain $D$, one can always construct a conjugate harmonic $v$ by integrating the Cauchy-Riemann equations along paths. The recipe is: choose a base point $(x_0, y_0) in D$, and for any $(x, y) in D$ define
#eq[$
  v(x, y) = integral_((x_0, y_0))^((x, y)) (-partial_y u) dif x + (partial_x u) dif y.
$] <eq:conj-harm-integral>
Because $u$ is harmonic, the vector field $(-partial_y u, partial_x u)$ is irrotational ($partial_x (partial_x u) - partial_y (-partial_y u) = nabla^2 u = 0$), and on a simply connected domain this guarantees that the line integral is independent of the chosen path, so that $v$ is well defined. One then checks that the partials of $v$ are exactly $-partial_y u$ and $partial_x u$, so the Cauchy-Riemann equations hold.

#example(name: "Recovering $z^2$ from Its Real Part")[
  Let $u(x, y) = x^2 - y^2$. A short computation shows that $nabla^2 u = 2 - 2 = 0$, so $u$ is harmonic on $bb(R)^2$. We find the conjugate harmonic by integrating along the polyline $(0, 0) -> (x, 0) -> (x, y)$ in @eq:conj-harm-integral:
  - Along the horizontal segment: $dif y = 0$, $-partial_y u = 2y = 0$, $partial_x u = 2x$. The integral contributes $0$.
  - Along the vertical segment: $dif x = 0$, $partial_x u = 2 x$. The integral contributes $integral_0^y 2 x dif t = 2 x y$.

  So $v(x, y) = 2 x y$ (up to an additive constant). Then
  $
    f(z) = u + "i"v = (x^2 - y^2) + "i" 2 x y = (x + "i"y)^2 = z^2,
  $
  which is indeed entire.
]

#note(title: "Milne-Thomson Method — A Practical Shortcut")[
  There is a handy "trick" for recovering the holomorphic function $f(z)$ directly from its real part $u(x, y)$, without performing the line integral @eq:conj-harm-integral: substitute
  $
    x = (z + overline(z))/2, quad y = (z - overline(z))/(2"i")
  $
  into $u(x, y)$, then formally set $overline(z) = 0$ (i.e., evaluate at $x = z/2$, $y = z/(2"i")$). More precisely, for a harmonic $u$ that is real-analytic near the origin,
  $
    f(z) = 2 u(z/2, z/(2"i")) - u(0, 0) + "i"C,
  $
  where $C in bb(R)$ is an arbitrary constant corresponding to the additive constant of the conjugate.

  Applying this to the previous example $u = x^2 - y^2$:
  $
    2 u(z/2, z/(2"i")) = 2 ((z/2)^2 - (z/(2"i"))^2) = 2(z^2/4 + z^2/4) = z^2,
  $
  and $u(0, 0) = 0$, giving $f(z) = z^2 + "i"C$, as expected.

  The method is particularly convenient when an explicit integral along a path would be messy. A rigorous justification relies on the identity theorem for analytic functions.
]

#note(title: "Physical Interpretations of Harmonic Functions")[
  Harmonic functions describe a wide variety of physical systems in two dimensions that are in *equilibrium*:
  - *Electrostatics.* In a charge-free region of the plane, the electrostatic potential $Phi(x, y)$ satisfies Laplace's equation $nabla^2 Phi = 0$. The conjugate harmonic of $Phi$ is the *stream function* of the electric field; together they form a *complex potential* $F = Phi + "i" Psi$, whose derivative $F'(z) = E_x - "i"E_y$ encodes the electric field.
  - *Stationary heat conduction.* In a region without heat sources or sinks, the equilibrium temperature distribution $T(x, y)$ obeys $nabla^2 T = 0$.
  - *Incompressible, irrotational fluid flow.* The velocity potential $phi$ and the stream function $psi$ are both harmonic, and their combination $f = phi + "i"psi$ is the complex velocity potential of the flow.

  In all these contexts, solving the Dirichlet problem (finding a harmonic function with prescribed boundary values) is of paramount importance; we return to this in Chapter 18.
]

#note(title: "Preview of Further Properties")[
  We conclude this chapter with a forward-looking list of additional properties of harmonic functions, to be established in Chapters 6 and 18 using the integral calculus of holomorphic functions:
  1. *Mean-value property.* For any disk contained in $D$, the value of a harmonic function at the center equals its average value on the boundary circle.
  2. *Maximum and minimum principle.* A non-constant harmonic function cannot attain a local maximum or minimum inside the domain; both extrema must lie on the boundary.
  3. *Smoothness.* Any harmonic function is automatically $C^oo$ and even real-analytic.
  4. *Harnack's inequality and Harnack's theorem.* These results control the growth of non-negative harmonic functions and yield compactness properties of families of harmonic functions.

  Each of these properties is a direct consequence of the corresponding statement for holomorphic functions, once one realizes that — locally at least — every harmonic function is the real part of some holomorphic function.
]

= Elementary Functions // 初等函数

== Exponential Function // 指数函数

== Trigonometric and Hyperbolic Functions // 三角函数与双曲函数

== Logarithmic Function // 对数函数

== Complex Powers // 复数幂

== Inverse Trigonometric Functions // 反三角函数

#part("Complex Integration") // 复积分
= Complex Integral // 复积分

== Definition and Properties of Complex Integral // 复积分的定义与性质
#definition(name: "Complex Integral")[
  Let $C: z=z(t), t in [alpha, beta]$ be an oriented curve in the complex plane starting at $a=z(alpha)$ and ending at $b=z(beta)$ and let $f(z)$ be a complex-valued function defined on $C$.

  From $a$ to $b$, take partitions of $C$ into $n$ segments by points $z_0=a, z_1, z_2, dots, z_n=b$.
  Then on each segment $z_(k-1)z_k$, take a point $xi_k$ and form the sum
  $
    sum_(k=1)^n f(xi_k)Delta z_(k), quad Delta z_(k) = z_k - z_(k-1).
  $
  If the limit of the above sum exists as the maximum length of the segments tends to zero, then we call it the *complex integral* of $f$ along $C$, denoted by
  $
    integral_C f(z) "d"z.
  $
]

#property[
  - *Linearity*: If $f$ and $g$ are integrable on $C$ and $alpha, beta in bb(C)$, then
  $
    integral_C (alpha f(z) + beta g(z)) "d"z = alpha integral_C f(z) "d"z + beta integral_C g(z) "d"z.
  $
  - *Additivity*: If $C$ is the union of two oriented curves $C_1$ and $C_2$ such that the end point of $C_1$ is the starting point of $C_2$, then
  $
    integral_C f(z) "d"z = integral_(C_1) f(z) "d"z + integral_(C_2) f(z) "d"z.
  $
  - *Reversal*: If $-C$ is the curve $C$ with the opposite orientation, then
  $
    integral_(-C) f(z) "d"z = - integral_C f(z) "d"z.
  $
  - *Estimation*: If $f$ is integrable on $C$, let $L$ be the length of $C$ and $M = max_(z in C) |f(z)|$, then
  $
    |integral_C f(z) "d"z| <= M L.
  $
]

#theorem[
  If $f(z) = u(x, y) + "i" v(x, y)$ is continuous on $C$, then $f$ is integrable on $C$ and
  $
    integral_C f(z) "d"z = integral_C u "d"x - integral_C v "d"y + "i" (integral_C v "d"x + integral_C u "d"y).
  $
]

#proposition(name: "Some Common Integrals")[
  - Let $C$ be any curve connecting $a$ and $b$, then
  $
    integral_C "d"z = b - a.
  $
  - Let $C$ be any curve connecting $a$ and $b$, then
  $
    integral_C z "d"z = (b^2 - a^2)/2.
  $
  - Let $C$ be a circle centered at the origin with radius $r$ and let $n in bb(C)$, then
  $
    integral_C 1/(z-a)^n "d"z = cases(
      0 & n != -1,
      2 pi"i" & n = -1
    )
  $
]

== Contour Integrals // 围道积分

== Path Independence // 路径无关性

= Cauchy's Theorem and Integral Formula // 柯西定理与积分公式

== Cauchy-Goursat Theorem // 柯西-古尔萨定理

#theorem(name: "Cauchy-Goursat Theorem")[
  If $f(z)$ is analytic in a simply connected domain $D$ and $C$ is a simple closed curve in $D$, then
  $
    integral_C f(z) "d"z = 0.
  $
]

== Cauchy Integral Formula and Its Derivatives // 柯西积分公式及其导数
#theorem(name: "Cauchy Integral Formula")[
  If $f(z)$ is analytic in a simply connected domain $D$ and continuous on $partial D$, and
  $C$ is a simple closed curve in $D$ that encloses a point $z_0$ (usually take $partial D$), then
  $
    f(z_0) = 1/(2 pi"i") integral_C f(z)/(z - z_0) "d"z.
  $
]

== Morera's Theorem // 莫雷拉定理

== Liouville's Theorem and Fundamental Theorem of Algebra // 刘维尔定理与代数基本定理

= Applications of Cauchy Integral Formula // 柯西积分公式的应用

== Maximum Modulus Principle and Mean Value Property // 最大模原理与平均值性质
#theorem(name: "Maximum Modulus Principle")[ // 最大模原理
  Let $f(z)$ be a non-constant analytic function in a bounded region $D subset CC$ that is continuous on the closure of $D$. Then the maximum of $|f(z)|$ on the closure of $D$ is attained on the boundary of $D$.
]

== Schwarz Lemma // 施瓦茨引理

== Weierstrass Convergence Theorem // 魏尔斯特拉斯收敛定理

#part("Series") // 级数
= Power Series and Taylor Series // 幂级数和泰勒级数
== Complex Series // 复级数
// 实数级数中, 只依赖距离和完备性的结论都能直接推广到复数级数 (绝对值替换成模); 但依赖序结构和特殊交错形式的结论不能。复数引入模后，许多判别法变得更统一，但条件收敛行为更复杂。
In real analysis, only the results that depend on completeness and distance can be directly extended to complex analysis (absolute value replaced by modulus); but the results that depend on order structure and special interleaving form cannot. After introducing the modulus, many criteria become more uniform, but the conditions of convergent behavior become more complex.

// 下面我们复级数区别于实数级数的部分
In the following, we will focus on the parts where complex series differ from real series.

=== Rearrangement of Series // 级数的重排
// 对于实数级数，条件收敛的级数可通过重排收敛到任意实数。
// 对于复数级数，情况更复杂（因为条件收敛的实部和虚部各自可能条件收敛），但绝对收敛的复数级数可以任意重排而不改变和，这和实数完全一样。
For real series, conditionally convergent series can be rearranged to converge to any real number.

For complex series, the situation is more complicated (because the real and imaginary parts of a conditionally convergent series may each be conditionally convergent), but absolutely convergent complex series can be rearranged arbitrarily without changing the sum, which is exactly the same as for real series.


== Radius of Convergence and Properties of Power Series // 收敛半径与幂级数的性质

=== Abel's Theorem for Power Series // 幂级数的阿贝尔定理

== Taylor Series

#theorem(name: "Taylor's Theorem")[
  Let $f(z)$ be holomorphic in region $D subset CC$ and $z_0 in D$. Then there exists the unique power series expansion of $f$ at $z_0$:
  $
    f(z) = sum_(n=0)^infinity c_n (z - z_0)^n,
  $
  where
  $
    c_n = 1/(2 pi "i") integral_(|z-z_0|=r) f(z)/(z-z_0)^(n+1) dif z = f^(n)(z_0)/n!,
  $
  and the radius of convergence of this power series is at least the distance from $z_0$ to the boundary of $D$.
]

== Isolation and Uniqueness of Zeros of Analytic Functions // 解析函数零点孤立性与唯一性
#definition(name: "m-th Order Zero")[ // m阶零点
  Let $f(z)$ be analytic in region $D subset CC$ and $z_0 in D$. We say that $z_0$ is an $m$-th order zero of $f$ if
  $
    f(z_0) = f'(z_0) = ... = f^(m-1)(z_0) = 0, quad f^(m)(z_0) != 0.
  $
]

#theorem[
  The point $z_0$ is an $m$-th order zero of the analytic function $f(z)$ that is not identically zero if and only if
  $
    f(z) = (z - z_0)^m g(z),
  $
  where $g(z)$ is analytic in a neighborhood of $z_0$ and $g(z_0) != 0$.
]

#theorem(name: "Isolation of Zeros")[
  Let $f(z)$ be an analytic function in region $D subset CC$ that is not identically zero. Then the zeros of $f$ are isolated, i.e., for each zero $z_0$ of $f$, there exists a neighborhood of $z_0$ that contains no other zeros of $f$.
]

#theorem(name: "Uniqueness of Zeros")[
  Let $f_1(z), f_2(z)$ be analytic functions in region $D subset CC$ that are not identically zero.
  There is a sequence ${z_n} (z!=z_0)$ that is converging to $z_0$ such that $f_1(z_n) = f_2(z_n) = 0$ for all $n$.
  Then $f_1(z) equiv f_2(z)$ for all $z in D$.
]

= Laurent Series // 洛朗级数
== Two-Sided Power Series and Laurent's Theorem // 双向幂级数与洛朗定理
Considering two series:
$
  c_0 + c_1 (z-z_0) + c_2 (z-z_0)^2 + ..., \
  c_{-1}/(z-z_0) + c_{-2}/(z-z_0)^2 + dots .
$
The first one is a power series, which stands for an analytic function $f_1(z)$ in a convergent disk $|z-z_0| < R (0<R<=infinity)$.
As for the second one, let $zeta = 1/(z-z_0)$, then it becomes a power series in $zeta$:
$
  c_{-1} zeta + c_{-2} zeta^2 + dots,
$
which stands for an analytic function $f_2(zeta)$ in a convergent disk $|zeta| < 1/r (0< 1/r <= infinity)$.
That is, the second series stands for an analytic function $f_2(z)$ in the region $|z-z_0| > r (0<r<=infinity)$.
If there exists a non-empty annulus $r < |z-z_0| < R$, then the sum of the two series, called a two-sided power series, denoted as

#eq[
  $
    sum_(n=-infinity)^infinity c_n (z-z_0)^n.
  $
] <two-sided-power-series>

#property[
  Let the convergent disk of series @two-sided-power-series be
  $
    H: r < |z-z_0| < R (0<=r<R<=infinity).
  $
  Then:
  + @two-sided-power-series absolutely converges and internally closed uniformly converges to $f(z) = f_1(z) + f_2(z)$ in $H$.
  + $f(z)$ is analytic in $H$ .
  + $f(z) = sum_(n=-infinity)^infinity c_n (z-z_0)^n$ in H can be termwise differentiated $p$ times.  // 函数在 H 内可以逐项求导 p 次
  + $f(z)$ can be integrated along any path in $H$, and the integral equals the sum of the integrals of the terms.
]

#theorem(name: "Laurent's Theorem")[
  Let $f(z)$ is analytic in the annulus $H: r < |z-z_0| < R (0<=r<R<=infinity)$.
  Then $f(z)$ can be represented as a two-sided power series:
  $
    f(z) = sum_(n=-infinity)^infinity c_n (z-z_0)^n,
  $
  where
  $
    c_n = 1/(2 pi"i") integral_(|z-z_0|=rho) f(z)/(z-z_0)^(n+1) dif z, quad r < rho < R, n = 0, plus.minus 1, plus.minus 2, ...
  $
]

== Classification of Singularities // 奇点的分类
#theorem(name: "Isolated Singularities")[
  Let $f(z)$ be an analytic function in the punctured disk $0 < |z-z_0| < R (0<R<=infinity)$.
  Then $z_0$ is called an isolated singularity of $f$.
]

If $z_0$ is an isolated singularity of $f$, then $f(z)$ can be represented as a Laurent series in the annulus $0 < |z-z_0| < R$.
There are two common methods to expand $f(z)$ into a Laurent series:
+ Method 1: Directly compute the coefficients $c_n$ using the integral formula.
+ Method 2: According to the uniqueness of the series composed of positive and negative power terms, use algebraic calculations, variable substitution, and Taylor expansion to obtain the Laurent series expansion. // 根据正负幂项组成的级数的唯一性, 使用代数计算、变量代换，并利用泰勒展开去求得洛朗展开式。

Let the Laurent series expansion of $f(z)$ at $z_0$ be
$
  f(z) = sum_(n=-infinity)^infinity c_n (z-z_0)^n.
$
Then we called non-minus power terms $c_n (z-z_0)^n$ the regular part of $f(z)$ at $z_0$, and the minus power terms $c_(-n) (z-z_0)^(-n)$ the principal part of $f(z)$ at $z_0$. Then we can classify the isolated singularity $z_0$ of $f(z)$ as follows:
+ If the principal part of $f(z)$ at $z_0$ is identically zero, i.e., $c_n = 0$ for all $n < 0$, then $z_0$ is called a *removable singularity* of $f(z)$.
+ If the principal part of $f(z)$ at $z_0$ has only finitely many non-zero terms, i.e., there exists a positive integer $m$ such that $c_n = 0$ for all $n < -m$, then $z_0$ is called a *pole* of order $m$ of $f(z)$.
+ If the principal part of $f(z)$ at $z_0$ has infinitely many non-zero terms, i.e., $c_n != 0$ for infinitely many negative integers $n$, then $z_0$ is called *essential singularity* of $f(z)$.

= Residue Theory // 留数理论

== Residues and Their Calculation // 留数及其计算

// 留数是洛朗展开中负一次项的系数，是连接级数表示与围道积分的关键工具。
#definition(name: "Residue")[
  Let $f(z)$ be analytic in the punctured disk $0 < abs(z - z_0) < R$, and let
  $
    f(z) = sum_(n=-infinity)^infinity c_n (z - z_0)^n
  $
  be its Laurent series at $z_0$ (see @two-sided-power-series). The coefficient $c_(-1)$ is called the *residue* of $f$ at $z_0$, denoted by
  $
    "Res"(f, z_0) = c_(-1).
  $
] <def:residue>

#property[
  - By the integral formula for Laurent coefficients, for any $0 < rho < R$,
    $
      "Res"(f, z_0) = 1/(2 pi"i") integral_(abs(z - z_0) = rho) f(z) dif z.
    $
  - If $z_0$ is a removable singularity of $f$, then $"Res"(f, z_0) = 0$.
]

#theorem(name: "Residues at Poles")[
  Let $z_0$ be a pole of $f$ of order $m$.
  + If $m = 1$ (*simple pole*), then
    $
      "Res"(f, z_0) = lim_(z -> z_0) (z - z_0) f(z).
    $
    In particular, if $f = P/Q$ with $P(z_0) != 0$ and $Q$ having a simple zero at $z_0$, then
    $
      "Res"(f, z_0) = P(z_0)/Q'(z_0).
    $
  + For a pole of order $m$,
    $
      "Res"(f, z_0) = 1/((m-1)!) lim_(z -> z_0) (dif^(m-1))/(dif z^(m-1)) [(z - z_0)^m f(z)].
    $
]

#theorem(name: "Logarithmic Derivative")[
  If $f$ has a zero of order $m$ at $z_0$, then $"Res"(f'/f, z_0) = m$; if $f$ has a pole of order $m$ at $z_0$, then $"Res"(f'/f, z_0) = -m$.
]

#example(name: "Residue of e^z/z^2 at 0")[
  Since
  $
    e^z/z^2 = 1/z^2 + 1/z + 1/2 + z/6 + dots,
  $
  the coefficient of $z^(-1)$ is $1$, so $"Res"(e^z/z^2, 0) = 1$.
]

#example(name: "Residue of 1/(z^2+1) at i")[
  The function $1/(z^2 + 1) = 1/((z - "i")(z + "i"))$ has simple poles at $z = plus.minus "i"$. Taking $P(z) = 1$ and $Q(z) = z^2 + 1$,
  $
    "Res"(1/(z^2 + 1), "i") = P("i")/Q'("i") = 1/(2"i") = -"i"/2.
  $
]

== Residue Theorem // 留数定理

// 留数定理将围道积分转化为被积函数在奇点处留数之和，是复分析中计算积分最核心的工具。
#theorem(name: "Residue Theorem")[
  Let $f(z)$ be analytic in a region $D$ except for a finite number of isolated singularities $z_1, z_2, dots, z_n$ inside $D$, and let $C$ be a positively oriented simple closed curve in $D$ that does not pass through any singularity. Then
  $
    integral_C f(z) dif z = 2 pi"i" sum_(k=1)^n "Res"(f, z_k),
  $
  where the sum is taken over the singularities $z_k$ enclosed by $C$.
] <thm:residue-theorem>

#proof[
  Enclose each singularity $z_k$ inside $C$ by a small positively oriented circle $C_k$ centered at $z_k$ such that the disks are pairwise disjoint and contained in the region bounded by $C$. Deforming the contour $C$ onto the circles $C_1, C_2, dots, C_n$ (a consequence of the Cauchy-Goursat theorem), we get
  $
    integral_C f(z) dif z = sum_(k=1)^n integral_(C_k) f(z) dif z.
  $
  On each $C_k$, expanding $f$ into its Laurent series at $z_k$ and integrating termwise (which is legitimate by the uniform convergence established in Ch8),
  $
    integral_(C_k) f(z) dif z = 2 pi"i" c_(-1)^((k)) = 2 pi"i" "Res"(f, z_k),
  $
  since all terms $(z - z_k)^n$ with $n != -1$ vanish on integration over a closed curve. Summing over $k$ yields the theorem.
]

// 扩充复平面上全部留数（含无穷远点）之和为零，这是留数定理的常用推论。
#corollary(name: "Sum of All Residues")[
  Define the residue of $f$ at infinity by
  $
    "Res"(f, infinity) = -"Res"(f(1/z)/z^2, 0).
  $
  If $f$ is meromorphic on the extended complex plane $hat(bb(C))$ with finitely many singularities, then
  $
    sum_(z in hat(bb(C))) "Res"(f, z) = 0,
  $
  where the sum is over all finite singularities together with the point at infinity.
]

#example(name: "Integral of 1/(z^2+1) over |z| = 2")[
  The function $f(z) = 1/(z^2 + 1)$ has simple poles at $plus.minus "i"$, both lying inside the circle $abs(z) = 2$. By the formula for $f = P/Q$ with $P(z) = 1$, $Q(z) = z^2 + 1$,
  $
    "Res"(f, "i") = P("i")/Q'("i") = 1/(2"i") = -"i"/2, quad "Res"(f, -"i") = P(-"i")/Q'(-"i") = -1/(2"i") = "i"/2.
  $
  Hence by #link(<thm:residue-theorem>)[the Residue Theorem],
  $
    integral_(abs(z) = 2) 1/(z^2 + 1) dif z = 2 pi"i" ("Res"(f, "i") + "Res"(f, -"i")) = 0.
  $
]

== Argument Principle // 辐角原理

// 环绕数（winding number）刻画一条闭曲线绕某点转过的圈数，是辐角原理的几何基础。
#definition(name: "Winding Number")[
  Let $C$ be a closed curve and let $z_0$ be a point not on $C$. The *winding number* of $C$ with respect to $z_0$ is defined as
  $
    "Ind"_C(z_0) = 1/(2 pi"i") integral_C dif z/(z - z_0).
  $
  For a simple closed curve $C$, $"Ind"_C(z_0) = 1$ if $z_0$ lies inside $C$ and $0$ otherwise.
]

// 辐角原理：亚纯函数沿闭曲线的对数导数积分等于内部零点数减去极点数。
#theorem(name: "Argument Principle")[
  Let $f(z)$ be meromorphic in a region $D$ and let $C$ be a positively oriented simple closed curve in $D$ that does not pass through any zero or pole of $f$. Then
  $
    1/(2 pi"i") integral_C f'(z)/f(z) dif z = N - P,
  $
  where $N$ and $P$ are the numbers of zeros and poles of $f$ inside $C$, counted with multiplicity.
] <thm:argument-principle>

#proof[
  Let $z_0$ be a zero of $f$ of order $m$. Then $f(z) = (z - z_0)^m g(z)$ with $g$ analytic and $g(z_0) != 0$, hence
  $
    f'(z)/f(z) = m/(z - z_0) + g'(z)/g(z),
  $
  where $g'/g$ is analytic at $z_0$. Thus $"Res"(f'/f, z_0) = m$. Similarly, at a pole of order $p$, $"Res"(f'/f, z_0) = -p$. Applying #link(<thm:residue-theorem>)[the Residue Theorem] to $f'/f$ gives
  $
    1/(2 pi"i") integral_C f'(z)/f(z) dif z = N - P.
  $
]

// 几何解释：沿 C 走一圈，f(z) 的辐角总变化量等于 2π(N-P)。
#note[
  Since $f'(z)/f(z) = (ln f(z))'$ locally, the integral above measures the total change of the argument of $f$ along $C$:
  $
    N - P = (Delta_C "Arg"(f))/(2 pi),
  $
  where $Delta_C "Arg"(f)$ is the change of the argument of $f(z)$ as $z$ traverses $C$ once. This explains the name of the principle.
]

#example(name: "Zeros Minus Poles of a Rational Function")[
  Let
  $
    f(z) = (z - 1)(z - 2)^2/((z + 1)(z + 2))
  $
  and let $C$ be the circle $abs(z) = 3$. Inside $C$, $f$ has zeros of total order $N = 1 + 2 = 3$ and poles of total order $P = 1 + 1 = 2$, so the argument principle gives
  $
    1/(2 pi"i") integral_C f'(z)/f(z) dif z = N - P = 1.
  $
]

== Rouché's Theorem // 儒歇定理

// 儒歇定理通过边界上的模比较来判定区域内零点个数，是辐角原理最重要的应用。
#theorem(name: "Rouché's Theorem")[
  Let $f(z)$ and $g(z)$ be analytic in a region $D$ and let $C$ be a positively oriented simple closed curve in $D$. If
  $
    abs(g(z)) < abs(f(z)) quad "for all" z in C,
  $
  then $f$ and $f + g$ have the same number of zeros inside $C$, counted with multiplicity.
] <thm:rouche>

#proof[
  On $C$, the inequality $abs(g) < abs(f)$ implies that neither $f$ nor $f + g$ vanishes on $C$. Moreover,
  $
    abs((f(z) + g(z))/f(z) - 1) = abs(g(z))/abs(f(z)) < 1,
  $
  so the curve $(f + g)/f(C)$ lies entirely inside the disk centered at $1$ with radius $1$, which does not contain $0$; hence $"Ind"_((f+g)/f)(0) = 0$. Applying #link(<thm:argument-principle>)[the Argument Principle] to $f + g$ and $f$ and subtracting,
  $
    N_(f+g) - N_f = 1/(2 pi"i") integral_C ((f + g)'/(f + g) - f'/f) dif z = 1/(2 pi"i") integral_C ((f + g)/f)'/((f + g)/f) dif z = 0.
  $
  Therefore $N_(f+g) = N_f$.
]

// 代数基本定理的另一个证明，与 Ch5 中刘维尔定理的证明互为补充。
#corollary(name: "Fundamental Theorem of Algebra")[
  Every polynomial $p(z) = a_n z^n + a_(n-1) z^(n-1) + dots + a_0$ with $a_n != 0$ has exactly $n$ zeros in $bb(C)$, counted with multiplicity.
]

#proof[
  Write $p = f + g$ with $f(z) = a_n z^n$ and $g(z) = a_(n-1) z^(n-1) + dots + a_0$. On a sufficiently large circle $abs(z) = R$,
  $
    abs(g(z)) <= sum_(k=0)^(n-1) abs(a_k) R^k < abs(a_n) R^n = abs(f(z)),
  $
  since the leading term dominates for large $R$. By #link(<thm:rouche>)[Rouché's Theorem], $p$ has as many zeros inside $abs(z) = R$ as $f(z) = a_n z^n$, namely $n$; letting $R -> infinity$ completes the proof.
]

#example(name: "Zeros of z^4 - 6z + 3 in the Unit Disk")[
  Let $p(z) = z^4 - 6z + 3$. Take $f(z) = -6z$ and $g(z) = z^4 + 3$. On the unit circle $abs(z) = 1$,
  $
    abs(g(z)) <= abs(z)^4 + 3 = 4 < 6 = abs(f(z)),
  $
  so by #link(<thm:rouche>)[Rouché's Theorem], $p$ has exactly one zero inside $abs(z) < 1$, the same as $f(z) = -6z$.
]

= Evaluation of Real Integrals // 实积分的计算

== Integrals of Rational Functions // 有理函数的积分

== Integrals Involving Trigonometric Functions // 含三角函数的积分

== Improper Integrals // 反常积分

== Integrals with Branch Cuts // 含割线的积分

== Summation of Series // 级数求和

#part("Conformal Mapping and Analytic Continuation") // 共形映射与解析延拓
= Theory of Conformal Mapping // 共形映射理论

= Elementary Conformal Mappings // 初等共形映射

= Analytic Continuation // 解析延拓

#part("Special Functions") // 特殊函数

= Gamma and Beta Functions // 伽马函数与贝塔函数

= Zeta Function and Prime Numbers // ζ函数与素数

= Elliptic Functions // 椭圆函数

#part("Advanced Topics") // 进阶主题

= Entire and Meromorphic Functions // 整函数与亚纯函数

= Harmonic Functions and Dirichlet Problem // 调和函数与狄利克雷问题

= Asymptotic Methods // 渐近方法



#bibliography("references.bib")

// 目录

// --- Part I: Basic Complex Analysis (基础复分析) ---

// Chapter 1: Complex Numbers and the Complex Plane (复数与复平面)
//   Section 1.1: Complex Numbers and Their Geometric Representation (复数与其几何表示)
//   Section 1.2: Polar Form and Euler's Formula (极坐标形式与欧拉公式)
//   Section 1.3: Powers and Roots of Complex Numbers (复数的幂与根)
//   Section 1.4: The Extended Complex Plane (扩充复平面)
//   Section 1.5: Topology of the Complex Plane (复平面的拓扑)

// Chapter 2: Complex Functions (复函数)
//   Section 2.1: Definition and Basic Properties (定义与基本性质)
//   Section 2.2: Limits and Continuity (极限与连续性)
//   Section 2.3: Differentiability and Analytic Functions (可微性与解析函数)
//   Section 2.4: Harmonic Functions (调和函数)

// Chapter 3: Elementary Functions (初等函数)
//   Section 3.1: Exponential Function (指数函数)
//   Section 3.2: Trigonometric and Hyperbolic Functions (三角函数与双曲函数)
//   Section 3.3: Logarithmic Function (对数函数)
//   Section 3.4: Complex Powers (复数幂)
//   Section 3.5: Inverse Trigonometric Functions (反三角函数)

// --- Part II: Complex Integration (复积分) ---

// Chapter 4: Complex Integral (复积分)
//   Section 4.1: Definition and Properties of Complex Integral (复积分的定义与性质)
//   Section 4.2: Contour Integrals (围道积分)
//   Section 4.3: Path Independence (路径无关性)

// Chapter 5: Cauchy's Theorem and Integral Formula (柯西定理与积分公式)
//   Section 5.1: Cauchy-Goursat Theorem (柯西-古尔萨定理)
//   Section 5.2: Cauchy Integral Formula and Its Derivatives (柯西积分公式及其导数)
//   Section 5.3: Morera's Theorem (莫雷拉定理)
//   Section 5.4: Liouville's Theorem and Fundamental Theorem of Algebra (刘维尔定理与代数基本定理)

// Chapter 6: Applications of Cauchy Integral Formula (柯西积分公式的应用)
//   Section 6.1: Maximum Modulus Principle and Mean Value Property (最大模原理与平均值性质)
//   Section 6.2: Schwarz Lemma (施瓦茨引理)
//   Section 6.3: Weierstrass Convergence Theorem (魏尔斯特拉斯收敛定理)

// --- Part III: Series (级数) ---

// Chapter 7: Power Series and Taylor Series (幂级数和泰勒级数)
//   Section 7.1: Complex Series (复级数)
//   Section 7.2: Radius of Convergence and Properties of Power Series (收敛半径与幂级数的性质)
//   Section 7.3: Taylor Series (泰勒级数)
//   Section 7.4: Isolation and Uniqueness of Zeros of Analytic Functions (解析函数零点孤立性与唯一性)

// Chapter 8: Laurent Series (洛朗级数)
//   Section 8.1: Two-Sided Power Series and Laurent's Theorem (双向幂级数与洛朗定理)
//   Section 8.2: Classification of Singularities (奇点的分类)

// Chapter 9: Residue Theory (留数理论)
//   Section 9.1: Residues and Their Calculation (留数及其计算)
//   Section 9.2: Residue Theorem (留数定理)
//   Section 9.3: Argument Principle (辐角原理)
//   Section 9.4: Rouché's Theorem (儒歇定理)

// Chapter 10: Evaluation of Real Integrals (实积分的计算)
//   Section 10.1: Integrals of Rational Functions (有理函数的积分)
//   Section 10.2: Integrals Involving Trigonometric Functions (含三角函数的积分)
//   Section 10.3: Improper Integrals (反常积分)
//   Section 10.4: Integrals with Branch Cuts (含割线的积分)
//   Section 10.5: Summation of Series (级数求和)

// --- Part IV: Conformal Mapping and Analytic Continuation (共形映射与解析延拓) ---

// Chapter 11: Theory of Conformal Mapping (共形映射理论)
//   Section 11.1: Conformal Mapping and Analytic Functions (共形映射与解析函数)
//   Section 11.2: Local Properties of Analytic Functions (解析函数的局部性质)
//   Section 11.3: Riemann Mapping Theorem (黎曼映射定理)
//   Section 11.4: Boundary Behavior (边界行为)
//   Section 11.5: Schwarz-Christoffel Transformation (施瓦茨-克里斯托费尔变换)

// Chapter 12: Elementary Conformal Mappings (初等共形映射)
//   Section 12.1: Linear Fractional Transformations (线性分式变换)
//   Section 12.2: Mappings to Canonical Domains (到标准区域的映射)
//   Section 12.3: Mappings of the Unit Disk (单位圆盘的映射)
//   Section 12.4: Mappings of the Upper Half-Plane (上半平面的映射)
//   Section 12.5: Applications to Potential Theory (在势论中的应用)

// Chapter 13: Analytic Continuation (解析延拓)
//   Section 13.1: Direct Analytic Continuation and Continuation along a Curve (直接解析延拓与沿曲线的解析延拓)
//   Section 13.2: Monodromy Theorem (单值性定理)
//   Section 13.3: Branch Points and Branch Cuts (支点与割线)
//   Section 13.4: Riemann Surfaces (黎曼曲面)
//   Section 13.5: Schwarz Reflection Principle (施瓦茨反射原理)

// --- Part V: Special Functions (特殊函数) ---

// Chapter 14: Gamma and Beta Functions (伽马函数与贝塔函数)
//   Section 14.1: Gamma Function (伽马函数)
//   Section 14.2: Properties of Gamma Function (伽马函数的性质)
//   Section 14.3: Beta Function (贝塔函数)
//   Section 14.4: Relation between Gamma and Beta Functions (伽马函数与贝塔函数的关系)
//   Section 14.5: Stirling's Formula (斯特林公式)

// Chapter 15: Zeta Function and Prime Numbers (ζ函数与素数)
//   Section 15.1: Riemann Zeta Function (黎曼ζ函数)
//   Section 15.2: Euler Product Formula (欧拉乘积公式)
//   Section 15.3: Functional Equation (函数方程)
//   Section 15.4: Riemann Hypothesis (黎曼猜想)
//   Section 15.5: Prime Number Theorem (素数定理)

// Chapter 16: Elliptic Functions (椭圆函数)
//   Section 16.1: Doubly Periodic Functions (双周期函数)
//   Section 16.2: Weierstrass ℘-Function (魏尔斯特拉斯℘函数)
//   Section 16.3: Jacobi Elliptic Functions (雅可比椭圆函数)
//   Section 16.4: Elliptic Integrals (椭圆积分)
//   Section 16.5: Applications (应用)

// --- Part VI: Advanced Topics (进阶主题) ---

// Chapter 17: Entire and Meromorphic Functions (整函数与亚纯函数)
//   Section 17.1: Weierstrass Factorization Theorem (魏尔斯特拉斯分解定理)
//   Section 17.2: Hadamard Factorization Theorem (阿达马分解定理)
//   Section 17.3: Order and Type of Entire Functions (整函数的阶与型)
//   Section 17.4: Mittag-Leffler Theorem (米塔格-莱夫勒定理)
//   Section 17.5: Picard's Theorems (皮卡定理)

// Chapter 18: Harmonic Functions and Dirichlet Problem (调和函数与狄利克雷问题)
//   Section 18.1: Harmonic Functions in the Plane (平面上的调和函数)
//   Section 18.2: Mean Value Property and Maximum Principle (平均值性质与最大值原理)
//   Section 18.3: Poisson Integral Formula (泊松积分公式)
//   Section 18.4: Dirichlet Problem for the Unit Disk (单位圆盘上的狄利克雷问题)
//   Section 18.5: Dirichlet Problem for General Domains (一般区域上的狄利克雷问题)

// Chapter 19: Asymptotic Methods (渐近方法)
//   Section 19.1: Method of Steepest Descent (最速下降法)
//   Section 19.2: Saddle Point Method (鞍点法)
//   Section 19.3: Watson's Lemma (沃森引理)
//   Section 19.4: Laplace's Method (拉普拉斯方法)
//   Section 19.5: Applications to Special Functions (在特殊函数中的应用)

// 结构说明：
// 本目录分为六个部分，共19章。Part I 建立复分析基础，从复数与复平面到复函数与初等函数；Part II 系统阐述复积分理论，包括复积分的定义、柯西定理与积分公式及其应用；Part III 讨论级数表示，涵盖幂级数、泰勒级数、洛朗级数、留数理论与实积分计算；Part IV 研究共形映射理论及其应用与解析延拓；Part V 介绍伽马函数、ζ函数与椭圆函数等特殊函数；Part VI 涵盖整函数、调和函数与渐近方法等进阶主题。整体编排遵循从基础到应用、从局部到整体、从经典到现代的逻辑主线。
